delete from ICD9_DISEASE;
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.4', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.5', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.6', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.4', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.5', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.6', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('143.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('143.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('143.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('143.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('144.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('144.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('144.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('144.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.4', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.5', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.6', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.4', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.5', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.6', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.7', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.2', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.3', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('149.0', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('149.1', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('149.8', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('149.9', 'Lip, Oral Cavity and Pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.0', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.1', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.2', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.3', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.4', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.5', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.8', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150.9', 'Esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.0', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.1', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.2', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.3', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.4', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.5', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.5', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.8', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151.9', 'Stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.0', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.1', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.2', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.3', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.8', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152.9', 'Small Intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.0', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.1', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.2', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.3', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.4', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.5', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.6', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.7', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.8', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153.9', 'Colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154.0', 'Rectum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154.1', 'Rectum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154.2', 'Anus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154.3', 'Anus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154.8', 'Anus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('155.0', 'Liver',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('155.1', 'Liver',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.0', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.1', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.2', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.3', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.4', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.8', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157.9', 'Pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('156.0', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('156.1', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('156.2', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('159.0', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('159.1', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('159.8', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('159.9', 'Other Digestive Organ',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.0', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.1', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.2', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.3', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.8', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.9', 'Larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.0', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.2', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.3', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.4', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161.5', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.8', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162.9', 'Lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.0', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.1', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.2', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.3', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.4', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.5', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.8', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160.9', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('163.0', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('163.1', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('163.8', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('163.9', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.0', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.1', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.2', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.3', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.8', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164.9', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('165.0', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('165.8', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('165.9', 'Other Respiratory and Intrathoracic Organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.0', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.1', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.2', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.3', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.4', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.5', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.6', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.7', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.8', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170.9', 'Bones and Joints',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('158.0', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('158.8', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('158.9', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('171.0', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('171.2', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('171.9', 'Soft Tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.0', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.1', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.2', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.3', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.4', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.5', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.6', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.7', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.8', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172.9', 'Melanoma, skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.0', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.1', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.2', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.3', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.4', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.5', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.8', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176.9', 'Kaposi’s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.1', 'Mycosis Fungoides',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.0', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.1', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.2', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.3', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.4', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.5', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.6', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.7', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.8', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.9', 'Other Skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.0', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.1', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.2', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.3', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.4', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.5', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.6', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.8', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174.9', 'Breast - Female',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('175.0', 'Breast - Male',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('175.9', 'Breast - Male',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('180.0', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('180.1', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('180.8', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('180.9', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('182.0', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('182.1', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('182.8', 'Cervix Uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.0', 'Ovary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('181.0', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.2', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.3', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.4', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.5', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.8', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183.9', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.0', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.1', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.2', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.3', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.4', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.8', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184.9', 'Other Female Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('185.0', 'Prtostate',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('186.0', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('186.9', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.1', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.2', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.3', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.4', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.5', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.6', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.7', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.8', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187.9', 'Other Male Genital',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.0', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.1', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.2', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.3', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.4', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.5', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.6', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.7', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.8', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188.9', 'Bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.0', 'Kidney',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.1', 'Kidney',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.2', 'Other Urinary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.3', 'Other Urinary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.4', 'Other Urinary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.8', 'Other Urinary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189.9', 'Other Urinary',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.0', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.1', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.2', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.3', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.4', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.5', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.6', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.7', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.8', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190.9', 'Eye and Orbit',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.0', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.1', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.2', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.3', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.4', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.5', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.6', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.7', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.8', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191.9', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.0', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.1', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.2', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.3', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.8', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192.9', 'Brain and Nervous System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('193.0', 'Thyroid',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.0', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.1', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.3', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.4', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.5', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.6', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.8', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194.9', 'Other Endocrine System',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.0', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.1', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.2', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.8', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.0', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.8', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.0', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.1', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.2', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.4', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.5', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.6', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.7', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.9', 'Non-Hodgkin’s Lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.0', 'Multiple Myeloma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.1', 'Multiple Myeloma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.0', 'Lymphoid Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.1', 'Lymphoid Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.2', 'Lymphoid Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.8', 'Lymphoid Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.9', 'Lymphoid Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.0', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.1', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.2', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.3', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.8', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.9', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.0', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.1', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.2', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.8', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.9', 'Myeloid and Monocytic Leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.4', 'Leukemia, other',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.0', 'Leukemia, other',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.1', 'Leukemia, other',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.2', 'Leukemia, other',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.8', 'Leukemia, other',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.0', 'Leukemia, not otherwise specified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.1', 'Leukemia, not otherwise specified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.2', 'Leukemia, not otherwise specified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.8', 'Leukemia, not otherwise specified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.9', 'Leukemia, not otherwise specified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.3', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.5', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.6', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.9', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.8', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('238.6', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('238.7', 'Other Hematopoietic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('199.0', 'Unknown Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('199.1', 'Unknown Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.0', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.1', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.2', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.3', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.4', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.5', 'Ill-Defined Sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195.8', 'Ill-Defined Sites',  now());