CREATE TABLE ICD9_DISEASE (
    IDENTIFIER SERIAL NOT NULL,
    DISEASE_CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED_ID INTEGER,
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED_ID INTEGER,
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE study_subject ADD COLUMN icd9disease_identifier BIGINT;

ALTER TABLE study_subject ADD CONSTRAINT fk_study_subject_icd9disease 
    FOREIGN KEY (icd9disease_identifier) REFERENCES icd9_disease (identifier) ON DELETE CASCADE;
