# whitelist
branches:
  only:
    - master
sudo: required
services:
  - docker
language: java
jdk:
  - openjdk7
before_install:
  - sudo apt-get install -y  awscli 
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DOCKER_IMAGE="ctrp/ctrp_4x_pa"
  - echo "TravisBuild=$TRAVIS_BUILD_NUMBER" > build_number.html &&
        echo "Commit=$TRAVIS_COMMIT" >> build_number.html       &&
        echo "TravisBuildID=$TRAVIS_BUILD_ID" >> build_number.html    &&
        echo "Author=$AUTHOR" >> build_number.html              &&
        echo "BuildTime=$DATE" >> build_number.html             &&
        echo "Docker=$DOCKER_IMAGE:$DATE" >> build_number.html
  - cat ./build_number.html
  #Set others
  - wget https://archive.apache.org/dist/maven/binaries/apache-maven-2.2.1-bin.tar.gz
  - tar xzvf apache-maven-2.2.1-bin.tar.gz
  - rm -rf $HOME/.m2
  - export M2_HOME=`pwd`/apache-maven-2.2.1
  - export M2=$M2_HOME/bin
  - export PATH=$M2:$PATH
  - export ANT_OPTS=-Dhttps.protocols=TLSv1.1,TLSv1.2
  - mvn -v
script:
  ###Build Script for PA
  - cd /home/travis/build/CBIIT/CTRP_4x_PA/build-pa
  - travis_wait 30 ant -v -d -f build-lite.xml get-artifacts > PA_build_output.txt
  - tail -n 100 PA_build_output.txt
  ###Run Unit Tests for PA
  #- cd /home/travis/build/CBIIT/CTRP_4x_PA/pa
  #- ant -f build.xml clean test >> PA_build_output.txt
  #- tail -n 100 PA_build_output.txt
  #Send build log to S3
  - aws s3 cp PA_build_output.txt s3://ctrp-repos-inttest/PA_build_output.txt --region us-east-1
  - find /home/travis/build/CBIIT/CTRP_4x_PA/target/
  #Build Docker image
  - cd /home/travis/build/CBIIT/CTRP_4x_PA/
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_failure:
  - cd /home/travis/build/CBIIT/CTRP_4x_PA/target/pa/
  - tar -zcf pa-build-reports.tar.gz reports/ 
  - aws s3 cp pa-build-reports.tar.gz s3://ctrp-repos-inttest/pa-build-reports.tar.gz --region us-east-1
after_success:
  # - bundle exec codeclimate-test-reporter
  #Push Docker image
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  #Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy
    --cluster CTRP-IntTest-Backend --service-name CTRP-ctrp_4x_pa-INTTEST 
    -i $DOCKER_IMAGE:$DATE
  #Trigger Travis bdd tests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" 
    -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" 
    -d "{\"request\":{\"message\":\"Triggered by CTRP_4x_PA $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=ctrp_4x_pa;TRIGGER_VER=$DATE;CUC_TAG=@pa;AUTHOR=$AUTHOR\"]}}}}" 
    https://api.travis-ci.org/repo/CBIIT%2Fctrp-bddtests/requests

# after_script:
notifications:
  slack: clinicalbiomed:W5L3wQ69vtL1XJCo8uT3oQgY
