drop sequence AUDIT_ID_SEQ;
drop table if exists dual_AUDIT_ID_SEQ;
create sequence AUDIT_ID_SEQ;
create table dual_AUDIT_ID_SEQ(test boolean);
drop table if exists prs_sync_history;

CREATE TABLE prs_sync_history (identifier INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, sync_date timestamp NOT NULL, data VARCHAR  NOT NULL);
CREATE ALIAS regexp_replace FOR "org.apache.commons.lang.StringUtils.replace";

alter table study_owner add column enable_emails bit DEFAULT true NOT NULL;
alter table csm_user add column automated_curation bit DEFAULT false NOT NULL;
alter table study_overall_status alter column deleted set not null;
alter table study_overall_status alter column deleted set default false;

DROP SEQUENCE nci_identifiers_seq IF EXISTS;
CREATE SEQUENCE nci_identifiers_seq;
CREATE UNIQUE INDEX idx01 ON study_protocol_flags (study_protocol_id, flag_reason, deleted);



alter table study_milestone add column admin boolean;
alter table study_milestone add column other boolean;
alter table study_milestone add column scientific boolean;
alter table study_overall_status add column current boolean;
alter table document_workflow_status add column current boolean;
alter table document_workflow_status add column previous boolean;

create view rv_active_milestone as
    SELECT    sm1.study_protocol_identifier, sm1.milestone_code, sm1.milestone_date
        FROM study_milestone sm1 WHERE (sm1.active = true);
        
create view rv_admin_milestone as 
	SELECT
	sm1.study_protocol_identifier, sm1.milestone_code, sm1.milestone_date
	FROM study_milestone sm1
	WHERE (sm1.admin = true);

create view rv_biomarker_existence as 
	SELECT
	sp.identifier AS study_protocol_identifier,
	true AS planned_marker_existence_indicator,
	min(pm.identifier) AS first_marker_id
	FROM      planned_marker pm       JOIN planned_activity pa ON pm.identifier = pa.identifier 
	   JOIN study_protocol sp ON pa.study_protocol_identifier = sp.identifier
	GROUP BY sp.identifier	;


create view rv_ccr_id as 
	SELECT
	ss.study_protocol_identifier, ss.local_sp_indentifier
	FROM
	
	      study_site ss
	      JOIN research_organization ro ON
	      ro.identifier = ss.research_organization_identifier
	   
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE
	(
	   ((ss.functional_code) = 'IDENTIFIER_ASSIGNER')
	   AND ((org.name) = 'NCI - Center for Cancer Research')
	)	;

create view rv_checkout_admin as 
	SELECT
	study_checkout.identifier,
	study_checkout.study_protocol_identifier,
	study_checkout.user_identifier,
	csm_user.first_name AS csm_first_name,
	csm_user.last_name AS csm_last_name,
	registry_user.first_name AS reg_first_name,
	registry_user.last_name AS reg_last_name,
	study_checkout.checkout_date
	FROM
	
	      study_checkout
	      LEFT JOIN csm_user ON
	      study_checkout.user_identifier = csm_user.login_name
	     
	   LEFT JOIN registry_user ON registry_user.csm_user_id = csm_user.user_id
	
	WHERE
	(
	   ((study_checkout.checkout_type) = 'ADMINISTRATIVE')
	   AND (study_checkout.checkin_date IS NULL)
	)	;


create view rv_checkout_scientific as 
	SELECT
	study_checkout.identifier,
	study_checkout.study_protocol_identifier,
	study_checkout.user_identifier,
	csm_user.first_name AS csm_first_name,
	csm_user.last_name AS csm_last_name,
	registry_user.first_name AS reg_first_name,
	registry_user.last_name AS reg_last_name,
	study_checkout.checkout_date
	FROM
	
	      study_checkout
	      LEFT JOIN csm_user ON
	      study_checkout.user_identifier = csm_user.login_name
	      
	   LEFT JOIN registry_user ON registry_user.csm_user_id = csm_user.user_id
	
	WHERE
	(
	   ((study_checkout.checkout_type) = 'SCIENTIFIC')
	   AND (study_checkout.checkin_date IS NULL)
	)	;

create view rv_ctep_id as 
	SELECT
	ss.study_protocol_identifier, ss.local_sp_indentifier
	FROM
	
	      study_site ss
	      JOIN research_organization ro ON
	      ro.identifier = ss.research_organization_identifier
	      
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE
	(
	   ((ss.functional_code) = 'IDENTIFIER_ASSIGNER')
	   AND ((org.name) = 'Cancer Therapy Evaluation Program')
	);
	
create view rv_dcp_id as	
	SELECT
	ss.study_protocol_identifier, ss.local_sp_indentifier
	FROM
	
	      study_site ss
	      JOIN research_organization ro ON
	     ro.identifier = ss.research_organization_identifier
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE
	(
	   ((ss.functional_code) = 'IDENTIFIER_ASSIGNER')
	   AND
	   (
	      (
	         org.name
	      )
	       = 'National Cancer Institute Division of Cancer Prevention'
	   )
	);
	
	
create view rv_dwf_current as
    SELECT
		dwf1.status_code, dwf1.status_date_range_low, dwf1.study_protocol_identifier
		FROM document_workflow_status dwf1
		WHERE (dwf1.current = true);
		
create view rv_dwf_previous as 
	SELECT
	dwf1.status_code, dwf1.status_date_range_low, dwf1.study_protocol_identifier
	FROM document_workflow_status dwf1
	WHERE (dwf1.previous = true)
	;
	
create view rv_last_hold as
	SELECT
	sh1.study_protocol_identifier,
	sh1.onhold_reason_code,
	sh1.onhold_date,
	sh1.offhold_date,
	sh1.onhold_reason_text,
	sh1.onhold_reason_category
	FROM study_onhold sh1
	WHERE	
	   sh1.identifier IN
	   (
	      SELECT
	      max(sh2.identifier) 
	      FROM study_onhold sh2
	      WHERE (sh1.study_protocol_identifier = sh2.study_protocol_identifier)
	   )	;
	   
create view rv_last_milestone as
	SELECT
	sm1.study_protocol_identifier, sm1.milestone_code, sm1.milestone_date
	FROM study_milestone sm1
	WHERE sm1.last = true	;
	
	
create view rv_lead_organization as
	SELECT
	ss.study_protocol_identifier,
	org.assigned_identifier,
	org.name,
	ss.local_sp_indentifier
	FROM
	
	  
	      study_site ss
	      JOIN research_organization ro ON
	     
	         ro.identifier = ss.research_organization_identifier
	     
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE ((ss.functional_code) = 'LEAD_ORGANIZATION');

create view rv_organization_responsible_party as
	SELECT
		ss.study_protocol_identifier,
		org.assigned_identifier,
		org.name,
		ss.local_sp_indentifier
	FROM	
	      study_site ss
	      JOIN research_organization ro ON
	     ro.identifier = ss.research_organization_identifier
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE ss.functional_code = 'RESPONSIBLE_PARTY_SPONSOR';

create view rv_other_milestone as
	SELECT
	sm1.study_protocol_identifier, sm1.milestone_code, sm1.milestone_date
	FROM study_milestone sm1
	WHERE sm1.other = true;

create view rv_principal_investigator_responsible_party as
	SELECT	sc.study_protocol_identifier, per.first_name, per.last_name	FROM	
		study_contact sc
		JOIN clinical_research_staff crs ON
		crs.identifier = sc.clinical_research_staff_identifier
		JOIN person per ON crs.person_identifier = per.identifier	
	WHERE
	(
	   (
	      (sc.role_code) = 'RESPONSIBLE_PARTY_STUDY_PRINCIPAL_INVESTIGATOR'
	   )
	   OR ((sc.role_code)= 'RESPONSIBLE_PARTY_SPONSOR_INVESTIGATOR')
	);

create view rv_scientific_milestone as 
	SELECT
	sm1.study_protocol_identifier, sm1.milestone_code, sm1.milestone_date
	FROM study_milestone sm1
	WHERE (sm1.scientific = true)
	;
	
create view rv_sos_current as SELECT sos1.status_code, sos1.study_protocol_identifier FROM study_overall_status sos1 WHERE (sos1.current = true) ;
create view rv_sponsor_organization as SELECT ss.study_protocol_identifier, org.assigned_identifier, org.name, ss.local_sp_indentifier
	FROM study_site ss JOIN research_organization ro ON ro.identifier = ss.research_organization_identifier
	JOIN organization org ON org.identifier = ro.organization_identifier	
	WHERE ((ss.functional_code) = 'SPONSOR');
	
create view rv_study_principal_investigator as
	SELECT
	sc.study_protocol_identifier, per.first_name, per.last_name
	FROM
	
	      study_contact sc
	      JOIN clinical_research_staff crs ON
	      crs.identifier = sc.clinical_research_staff_identifier
	   JOIN person per ON crs.person_identifier = per.identifier	
	WHERE ((sc.role_code) = 'STUDY_PRINCIPAL_INVESTIGATOR')	;

create view rv_study_resourcing as
	SELECT
	sr.study_protocol_identifier, sr.type_code
	FROM study_resourcing sr
	WHERE
	(
	   (sr.summ_4_rept_indicator = true)
	   AND
	   (
	      sr.identifier IN
	      (
	         SELECT
	         max(sr2.identifier) 
	         FROM study_resourcing sr2
	         WHERE
	         (
	            (sr.study_protocol_identifier = sr2.study_protocol_identifier)
	            AND (sr2.summ_4_rept_indicator = true)
	         )
	      )
	   )
	);

create view rv_trial_id_cdr as
	SELECT
	soi1.study_protocol_id, soi1.extension
	FROM study_otheridentifiers soi1
	WHERE
	(
	   (substr((soi1.extension), 1, 3) = 'CDR')
	   AND
	   (
	      (
	         soi1.extension
	      )
	       =
	      (
	         (
	            SELECT
	            soi2.extension
	            FROM study_otheridentifiers soi2
	            WHERE
	            (
	               (substr((soi2.extension), 1, 3) = 'CDR')
	               AND (soi2.study_protocol_id = soi1.study_protocol_id)
	            )
	            LIMIT 1
	         )
	      )
	      
	   )
	);
	
create view rv_trial_id_nci as
	SELECT
	study_otheridentifiers.study_protocol_id, study_otheridentifiers.extension
	FROM study_otheridentifiers
	WHERE ((study_otheridentifiers.root) = '2.16.840.1.113883.3.26.4.3');

create view rv_trial_id_nct as
	SELECT
	ss.study_protocol_identifier, ss.local_sp_indentifier
	FROM
	
	      study_site ss
	      JOIN research_organization ro ON
	      ro.identifier = ss.research_organization_identifier
	   JOIN organization org ON org.identifier = ro.organization_identifier
	
	WHERE
	(
	   ((org.name) = 'ClinicalTrials.gov')
	   AND ((ss.functional_code) = 'IDENTIFIER_ASSIGNER')
	);

create view rv_trial_submitter as
	SELECT
		sp.identifier AS study_protocol_identifier,
		ru.identifier AS submitter_id,
		ru.first_name AS submitter_fname,
		ru.last_name AS submitter_lname,
		o.name AS submitter_org_name,
		o.assigned_identifier AS submitter_org_id
	FROM registry_user ru JOIN csm_user cu ON cu.user_id = ru.csm_user_id
	   JOIN study_protocol sp ON sp.user_last_created_id = cu.user_id	   
	   JOIN organization o ON o.identifier = sp.submitting_organization_id	;

create view rv_updating_trials as 
SELECT
DISTINCT study_inbox.study_protocol_identifier, true AS updating
FROM study_inbox
WHERE (study_inbox.close_date IS NULL);

CREATE VIEW rv_search_results AS 
 SELECT sp.identifier AS study_protocol_identifier, sp.official_title, 
    sp.proprietary_trial_indicator, sp.record_verification_date, 
    sp.date_last_created, sp.submission_number, sp.ctgov_xml_required_indicator, 
    upd.updating, nciid.extension AS nci_number, 
    nctid.local_sp_indentifier AS nct_number, 
    lo.assigned_identifier AS lead_org_poid, lo.name AS lead_org_name, 
    lo.local_sp_indentifier AS lead_org_sp_identifier, 
    dwf.status_code AS current_dwf_status_code, 
    dwf.status_date_range_low AS current_dwf_status_date, 
    sos.status_code AS current_study_overall_status, 
    ams.milestone_code AS current_admin_milestone, 
    sms.milestone_code AS current_scientific_milestone, 
    oms.milestone_code AS current_other_milestone, 
    coa.identifier AS admin_checkout_identifier, 
    coa.user_identifier AS admin_checkout_user, 
    cos.identifier AS scientific_checkout_identifier, 
    cos.user_identifier AS scientific_checkout_user, 
    spi.first_name AS study_pi_first_name, spi.last_name AS study_pi_last_name, 
    usr.login_name AS user_last_created_login, 
    usr.first_name AS user_last_created_first, 
    usr.last_name AS user_last_created_last, dcp.local_sp_indentifier AS dcp_id, 
    ctep.local_sp_indentifier AS ctep_id, sp.amendment_date, 
    sp.date_last_updated, sp.phase_code, sp.primary_purpose_code, sp.start_date, 
    sr.type_code AS summary4fundingsponsor_type, so.name AS sponsor_name, 
    orp.name AS responsible_party_organization_name, 
    pirp.first_name AS responsible_party_pi_first_name, 
    pirp.last_name AS responsible_party_pi_last_name, 
    usr.login_name AS user_last_updated_login, 
    usr.first_name AS user_last_updated_first, 
    usr.last_name AS user_last_updated_last, 
    sp.pri_compl_date AS primary_completion_date, sp.study_protocol_type, 
    sp.study_subtype_code, ts.submitter_org_name, 
    ams.milestone_date AS current_admin_milestone_date, 
    sms.milestone_date AS current_scientific_milestone_date, 
    oms.milestone_date AS current_other_milestone_date, sp.processing_priority, 
    lms.milestone_code AS last_milestone, 
    lms.milestone_date AS last_milestone_date, 
    actms.milestone_code AS active_milestone, 
    actms.milestone_date AS active_milestone_date, 
    coa.csm_first_name AS admin_checkout_csm_fname, 
    coa.csm_last_name AS admin_checkout_csm_lname, 
    coa.reg_first_name AS admin_checkout_reg_fname, 
    coa.reg_last_name AS admin_checkout_reg_lname, 
    cos.csm_first_name AS scientific_checkout_csm_fname, 
    cos.csm_last_name AS scientific_checkout_csm_lname, 
    cos.reg_first_name AS scientific_checkout_reg_fname, 
    cos.reg_last_name AS scientific_checkout_reg_lname, hold.onhold_reason_code, 
    hold.onhold_date, hold.offhold_date, cdr.extension AS cdr_id, 
    sp.amendment_number, coa.checkout_date AS admin_checkout_date, 
    cos.checkout_date AS scientific_checkout_date, sp.comments, 
    hold.onhold_reason_text, false AS planned_marker_existence_indicator, 
    sp.study_source, ccr.local_sp_indentifier AS ccr_id, 
    sp.accrual_disease_code_system, 
    prev_dwf.status_code AS previous_dwf_status_code, 
    ts.submitter_org_id AS submiting_org_id,
    hold.onhold_reason_category,
    sp.expected_abstraction_completion_date,
    sp.expected_abstraction_completion_comments,
    sp.pcd_sent_to_pio_date AS pcd_sent_to_pio_date,
    sp.pcd_confirm_date AS pcd_confirm_date,
    sp.designee_notified_date AS designee_notified_date,
    sp.reporting_in_process_date AS reporting_in_process_date,
    sp.three_month_reminder_date AS three_month_reminder_date,
    sp.five_month_reminder_date AS five_month_reminder_date,
    sp.seven_month_escalation_to_pio_date AS seven_month_escalation_to_pio_date,
    sp.results_sent_to_pio_date AS results_sent_to_pio_date,
    sp.results_approved_by_pio_date AS results_approved_by_pio_date,
    sp.prs_release_date AS prs_release_date,
    sp.qa_comments_return_date AS qa_comments_return_date,
    sp.trial_published_date AS trial_published_date

   FROM study_protocol sp
   LEFT JOIN rv_updating_trials upd ON sp.identifier = upd.study_protocol_identifier
   LEFT JOIN rv_trial_id_nci nciid ON sp.identifier = nciid.study_protocol_id
   LEFT JOIN rv_trial_id_nct nctid ON sp.identifier = nctid.study_protocol_identifier
   LEFT JOIN rv_lead_organization lo ON sp.identifier = lo.study_protocol_identifier
   LEFT JOIN rv_dwf_current dwf ON sp.identifier = dwf.study_protocol_identifier
   LEFT JOIN rv_sos_current sos ON sp.identifier = sos.study_protocol_identifier
   LEFT JOIN rv_admin_milestone ams ON sp.identifier = ams.study_protocol_identifier
   LEFT JOIN rv_scientific_milestone sms ON sp.identifier = sms.study_protocol_identifier
   LEFT JOIN rv_other_milestone oms ON sp.identifier = oms.study_protocol_identifier
   LEFT JOIN rv_last_milestone lms ON sp.identifier = lms.study_protocol_identifier
   LEFT JOIN rv_active_milestone actms ON sp.identifier = actms.study_protocol_identifier
   LEFT JOIN rv_checkout_admin coa ON sp.identifier = coa.study_protocol_identifier
   LEFT JOIN rv_checkout_scientific cos ON sp.identifier = cos.study_protocol_identifier
   LEFT JOIN rv_study_principal_investigator spi ON sp.identifier = spi.study_protocol_identifier
   LEFT JOIN csm_user usr ON sp.user_last_created_id = usr.user_id
   LEFT JOIN rv_dcp_id dcp ON sp.identifier = dcp.study_protocol_identifier
   LEFT JOIN rv_ctep_id ctep ON sp.identifier = ctep.study_protocol_identifier
   LEFT JOIN rv_study_resourcing sr ON sp.identifier = sr.study_protocol_identifier
   LEFT JOIN rv_sponsor_organization so ON sp.identifier = so.study_protocol_identifier
   LEFT JOIN rv_organization_responsible_party orp ON sp.identifier = orp.study_protocol_identifier
   LEFT JOIN rv_principal_investigator_responsible_party pirp ON sp.identifier = pirp.study_protocol_identifier
   LEFT JOIN rv_trial_submitter ts ON sp.identifier = ts.study_protocol_identifier
   LEFT JOIN rv_last_hold hold ON sp.identifier = hold.study_protocol_identifier
   LEFT JOIN rv_trial_id_cdr cdr ON sp.identifier = cdr.study_protocol_id
   LEFT JOIN rv_ccr_id ccr ON sp.identifier = ccr.study_protocol_identifier
   LEFT JOIN rv_dwf_previous prev_dwf ON sp.identifier = prev_dwf.study_protocol_identifier;  



CREATE TRIGGER study_milestone_set_active_trigger_insert AFTER INSERT ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_active_study_milestone";    
CREATE TRIGGER study_milestone_set_active_trigger_update AFTER UPDATE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_active_study_milestone";
CREATE TRIGGER study_milestone_set_active_trigger_delete AFTER DELETE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_active_study_milestone";

CREATE TRIGGER study_milestone_set_admin_trigger_insert AFTER INSERT ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_admin_study_milestone";    
CREATE TRIGGER study_milestone_set_admin_trigger_update AFTER UPDATE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_admin_study_milestone";
CREATE TRIGGER study_milestone_set_admin_trigger_delete AFTER DELETE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_admin_study_milestone";

CREATE TRIGGER study_milestone_set_last_trigger_insert AFTER INSERT ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_last_study_milestone";    
CREATE TRIGGER study_milestone_set_last_trigger_update AFTER UPDATE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_last_study_milestone";
CREATE TRIGGER study_milestone_set_last_trigger_delete AFTER DELETE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_last_study_milestone";

CREATE TRIGGER study_milestone_set_other_trigger_insert AFTER INSERT ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_other_study_milestone";    
CREATE TRIGGER study_milestone_set_other_trigger_update AFTER UPDATE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_other_study_milestone";
CREATE TRIGGER study_milestone_set_other_trigger_delete AFTER DELETE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_other_study_milestone";

CREATE TRIGGER study_milestone_set_scientific_trigger_insert AFTER INSERT ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_scientific_study_milestone";    
CREATE TRIGGER study_milestone_set_scientific_trigger_update AFTER UPDATE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_scientific_study_milestone";
CREATE TRIGGER study_milestone_set_scientific_trigger_delete AFTER DELETE ON study_milestone FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_scientific_study_milestone";

CREATE TRIGGER study_overall_status_set_current_trigger_insert AFTER INSERT ON study_overall_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_study_overall_status";    
CREATE TRIGGER study_overall_status_set_current_trigger_update AFTER UPDATE ON study_overall_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_study_overall_status";
CREATE TRIGGER study_overall_status_set_current_trigger_delete AFTER DELETE ON study_overall_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_study_overall_status";

CREATE TRIGGER document_workflow_status_set_current_trigger_insert AFTER INSERT ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_document_workflow_status";    
CREATE TRIGGER document_workflow_status_set_current_trigger_update AFTER UPDATE ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_document_workflow_status";
CREATE TRIGGER document_workflow_status_set_current_trigger_delete AFTER DELETE ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_current_document_workflow_status";

CREATE TRIGGER document_workflow_status_set_previous_trigger_insert AFTER INSERT ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_previous_document_workflow_status";    
CREATE TRIGGER document_workflow_status_set_previous_trigger_update AFTER UPDATE ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_previous_document_workflow_status";
CREATE TRIGGER document_workflow_status_set_previous_trigger_delete AFTER DELETE ON document_workflow_status FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.set_previous_document_workflow_status";

CREATE TRIGGER sync_trial_nci_id_trigger_insert AFTER INSERT ON STUDY_OTHERIDENTIFIERS FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_nci_id";    
CREATE TRIGGER sync_trial_nci_id_trigger_update AFTER UPDATE ON STUDY_OTHERIDENTIFIERS FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_nci_id";
CREATE TRIGGER sync_trial_nci_id_trigger_delete AFTER DELETE ON STUDY_OTHERIDENTIFIERS FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_nci_id";

CREATE TRIGGER sync_trial_identifier_assigner_ids_trigger_insert AFTER INSERT ON STUDY_SITE FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_identifier_assigner_ids";    
CREATE TRIGGER sync_trial_identifier_assigner_ids_triggerr_update AFTER UPDATE ON STUDY_SITE FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_identifier_assigner_ids";
CREATE TRIGGER sync_trial_identifier_assigner_ids_trigger_delete AFTER DELETE ON STUDY_SITE FOR EACH ROW QUEUE 0 CALL "gov.nih.nci.pa.util.testsupport.sync_trial_identifier_assigner_ids";



