//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "gov.nih.nci.po.webservices.types.trimmed", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nih.nci.po.webservices.types;
