CREATE TABLE PLANNED_MARKER (  
    IDENTIFIER SERIAL NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    LONG_NAME VARCHAR(1000),
    HUGO_BIOMARKER_CODE VARCHAR(200),
    ASSAY_TYPE_CODE VARCHAR(200) NOT NULL,
    ASSAY_TYPE_OTHER_TEXT VARCHAR(200),
    ASSAY_USE_CODE VARCHAR(200) NOT NULL,
    ASSAY_PURPOSE_CODE VARCHAR(200) NOT NULL,
    ASSAY_PURPOSE_OTHER_TEXT VARCHAR(200),
    TISSUE_SPECIMEN_TYPE_CODE VARCHAR(200) NOT NULL,
    TISSUE_COLLECTION_METHOD_CODE VARCHAR(200) NOT NULL,
    STATUS_CODE VARCHAR(200) NOT NULL,
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE PLANNED_MARKER ADD CONSTRAINT FK_PLANNED_MARKER_PLANNED_ACTIVITY 
    FOREIGN KEY (IDENTIFIER) REFERENCES PLANNED_ACTIVITY (IDENTIFIER) ON DELETE CASCADE;
