CREATE TABLE PLANNED_PROCEDURE  (
    IDENTIFIER SERIAL NOT NULL,
    TARGET_SITE_CODE VARCHAR(200),
    METHOD_CODE VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE PLANNED_ELIGIBILITY_CRITERION (
    IDENTIFIER SERIAL NOT NULL,
    INCLUSION_INDICATOR BOOLEAN,
    CRITERION_NAME VARCHAR(200),
    OPERATOR VARCHAR(200),
    ELIGIBLE_GENDER_CODE VARCHAR(200),
    MIN_VALUE NUMERIC,
    MIN_UNIT VARCHAR(200),
    MAX_VALUE NUMERIC,
    MAX_UNIT VARCHAR(200),
    UNIT VARCHAR(200),
    DISPLAY_ORDER BIGINT,
    STRUCTURED_INDICATOR BOOLEAN,
    TEXT_VALUE VARCHAR(5000),
    CDE_PUBLIC_IDENTIFIER NUMERIC,
    CDE_VERSION_NUMBER VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE PLANNED_SUBSTANCE_ADMINISTRATION ( 
    IDENTIFIER SERIAL NOT NULL,
    DOSE_MIN_VALUE NUMERIC,
    DOSE_MIN_UNIT VARCHAR(200),
    DOSE_MAX_VALUE NUMERIC,
    DOSE_MAX_UNIT VARCHAR(200),
    DOSE_DESCRIPTION VARCHAR(5000),
    DOSE_FORM_CODE VARCHAR(200),
    DOSE_FREQUENCY_CODE VARCHAR(200),
    DOSE_REGIMEN VARCHAR(1000),
    DOSE_TOTAL_MIN_VALUE NUMERIC,
    DOSE_TOTAL_MIN_UNIT VARCHAR(200),
    DOSE_TOTAL_MAX_VALUE NUMERIC,
    DOSE_TOTAL_MAX_UNIT VARCHAR(200),
    ROUTE_OF_ADMINISTRATION_CODE VARCHAR(200),
    DOSE_DURATION_VALUE NUMERIC,
    DOSE_DURATION_UNIT VARCHAR(200),
    TARGET_SITE_CODE VARCHAR(200),
    APPROACH_SITE_CODE VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE PLANNED_PROCEDURE ADD CONSTRAINT FK_PLANNED_PROCEDURE_PLANNED_ACTIVITY 
    FOREIGN KEY (IDENTIFIER) REFERENCES PLANNED_ACTIVITY (IDENTIFIER) ON DELETE CASCADE;
ALTER TABLE PLANNED_PROCEDURE ADD CONSTRAINT fk_planned_procedure_target_site_code 
    FOREIGN KEY (TARGET_SITE_CODE) REFERENCES TARGET_SITE(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_PROCEDURE ADD CONSTRAINT fk_planned_procedure_method_code 
    FOREIGN KEY (METHOD_CODE) REFERENCES METHOD_CODE(code) ON DELETE RESTRICT;
    
ALTER TABLE PLANNED_ELIGIBILITY_CRITERION ADD CONSTRAINT FK_PLANNED_ELIGIBILITY_CRITERION_PLANNED_ACTIVITY 
    FOREIGN KEY (IDENTIFIER) REFERENCES PLANNED_ACTIVITY (IDENTIFIER) ON DELETE CASCADE;    
    
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT FK_PLANNED_SUBSTRANCE_ADMINISTRATION_PLANNED_ACTIVITY 
    FOREIGN KEY (IDENTIFIER) REFERENCES PLANNED_ACTIVITY (IDENTIFIER) ON DELETE CASCADE;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_form_code 
    FOREIGN KEY (DOSE_FORM_CODE) REFERENCES DOSE_FORM(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_frequency_code 
    FOREIGN KEY (DOSE_FREQUENCY_CODE) REFERENCES DOSE_FREQUENCY(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_max_unit 
    FOREIGN KEY (DOSE_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_min_unit 
    FOREIGN KEY (DOSE_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_total_max_unit 
    FOREIGN KEY (DOSE_TOTAL_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_dose_total_min_unit 
    FOREIGN KEY (DOSE_TOTAL_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_target_site_code 
    FOREIGN KEY (TARGET_SITE_CODE) REFERENCES TARGET_SITE(code) ON DELETE RESTRICT;   
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_approach_site_code 
    FOREIGN KEY (APPROACH_SITE_CODE) REFERENCES TARGET_SITE(code) ON DELETE RESTRICT;
ALTER TABLE PLANNED_SUBSTANCE_ADMINISTRATION ADD CONSTRAINT fk_planned_substrance_administration_route_of_administration_code 
    FOREIGN KEY (ROUTE_OF_ADMINISTRATION_CODE) REFERENCES ROUTE_OF_ADMINISTRATION(code) ON DELETE RESTRICT;
    
INSERT INTO PLANNED_PROCEDURE (IDENTIFIER, TARGET_SITE_CODE, METHOD_CODE) 
    SELECT IDENTIFIER, TARGET_SITE_CODE, METHOD_CODE FROM PLANNED_ACTIVITY WHERE PLANNED_ACTIVITY_TYPE = 'PlannedProcedure';

INSERT INTO PLANNED_ELIGIBILITY_CRITERION (IDENTIFIER, INCLUSION_INDICATOR, CRITERION_NAME, OPERATOR, ELIGIBLE_GENDER_CODE, MIN_VALUE,
    MIN_UNIT, MAX_VALUE, MAX_UNIT, UNIT, DISPLAY_ORDER, STRUCTURED_INDICATOR, TEXT_VALUE, CDE_PUBLIC_IDENTIFIER, 
    CDE_VERSION_NUMBER) SELECT IDENTIFIER, INCLUSION_INDICATOR, CRITERION_NAME, OPERATOR, ELIGIBLE_GENDER_CODE, MIN_VALUE,
    MIN_UNIT, MAX_VALUE, MAX_UNIT, UNIT, DISPLAY_ORDER, STRUCTURED_INDICATOR, TEXT_VALUE, CDE_PUBLIC_IDENTIFIER, 
    CDE_VERSION_NUMBER FROM PLANNED_ACTIVITY WHERE PLANNED_ACTIVITY_TYPE = 'PlannedEligibilityCriterion';

INSERT INTO PLANNED_SUBSTANCE_ADMINISTRATION (IDENTIFIER, DOSE_MIN_VALUE, DOSE_MIN_UNIT, DOSE_MAX_VALUE, DOSE_MAX_UNIT,
    DOSE_DESCRIPTION, DOSE_FORM_CODE, DOSE_FREQUENCY_CODE, DOSE_REGIMEN, DOSE_TOTAL_MIN_VALUE, DOSE_TOTAL_MIN_UNIT,
    DOSE_TOTAL_MAX_VALUE, DOSE_TOTAL_MAX_UNIT, ROUTE_OF_ADMINISTRATION_CODE, DOSE_DURATION_VALUE, DOSE_DURATION_UNIT,
    TARGET_SITE_CODE, APPROACH_SITE_CODE) SELECT IDENTIFIER, DOSE_MIN_VALUE, DOSE_MIN_UNIT, DOSE_MAX_VALUE, DOSE_MAX_UNIT,
    DOSE_DESCRIPTION, DOSE_FORM_CODE, DOSE_FREQUENCY_CODE, DOSE_REGIMEN, DOSE_TOTAL_MIN_VALUE, DOSE_TOTAL_MIN_UNIT,
    DOSE_TOTAL_MAX_VALUE, DOSE_TOTAL_MAX_UNIT, ROUTE_OF_ADMINISTRATION_CODE, DOSE_DURATION_VALUE, DOSE_DURATION_UNIT,
    TARGET_SITE_CODE, APPROACH_SITE_CODE FROM PLANNED_ACTIVITY WHERE PLANNED_ACTIVITY_TYPE = 'PlannedSubstanceAdministration';
    
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN TARGET_SITE_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN METHOD_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN INCLUSION_INDICATOR;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN CRITERION_NAME;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN OPERATOR;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN ELIGIBLE_GENDER_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN MIN_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN MIN_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN MAX_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN MAX_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DISPLAY_ORDER;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN STRUCTURED_INDICATOR;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN TEXT_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN CDE_PUBLIC_IDENTIFIER;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN CDE_VERSION_NUMBER;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_MIN_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_MIN_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_MAX_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_MAX_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_DESCRIPTION;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_FORM_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_FREQUENCY_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_REGIMEN; 
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_TOTAL_MIN_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_TOTAL_MIN_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_TOTAL_MAX_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_TOTAL_MAX_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN ROUTE_OF_ADMINISTRATION_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_DURATION_VALUE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN DOSE_DURATION_UNIT;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN APPROACH_SITE_CODE;
ALTER TABLE PLANNED_ACTIVITY DROP COLUMN PLANNED_ACTIVITY_TYPE;
