ALTER TABLE STUDY_PROTOCOL 	ADD COLUMN STATUS_CODE VARCHAR(200),
	ADD COLUMN STATUS_DATE TIMESTAMP,
	ADD COLUMN AMENDMENT_NUMBER VARCHAR(200),
	ADD COLUMN AMENDMENT_DATE TIMESTAMP,
	ADD COLUMN AMENDMENT_REASON_CODE VARCHAR(200),
	ADD COLUMN SUBMISSION_NUMBER INTEGER,
	ADD COLUMN PARENT_PROTOCOL_IDENTIFIER VARCHAR(200);
  	
	