ALTER TABLE STUDY_PARTICIPATION  ADD COLUMN STATUS_DATE_RANGE_HIGH  TIMESTAMP;

ALTER TABLE STUDY_CONTACT  ADD COLUMN STATUS_DATE_RANGE_HIGH  TIMESTAMP;

ALTER TABLE STUDY_PARTICIPATION_CONTACT  ADD COLUMN STATUS_DATE_RANGE_HIGH  TIMESTAMP;