CREATE TABLE STUDY_SUMMARY_FOUR_ORG_IDENTIFIER_STAGE
(
  STUDY_PROTOCOL_ID BIGINT NOT NULL,
  SUMMARY_FOUR_ORG_IDENTIFIER character varying(50),
  CONSTRAINT STUDY_SFOI_STAGE_FK FOREIGN KEY (STUDY_PROTOCOL_ID)
      REFERENCES STUDY_PROTOCOL_STAGE (IDENTIFIER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO STUDY_SUMMARY_FOUR_ORG_IDENTIFIER_STAGE (STUDY_PROTOCOL_ID, SUMMARY_FOUR_ORG_IDENTIFIER)
SELECT identifier, summary_four_org_identifier FROM study_protocol_stage;
    
ALTER TABLE study_protocol_stage DROP COLUMN summary_four_org_identifier;
ALTER TABLE study_protocol_stage DROP COLUMN site_summary_four_org_identifier;