//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A request to update an Abbreviated trial in CTRP. An
 * 				update permits trial owners to change a very limited set
 * 				of data
 * 				element
 * 				of an Abbreviated trial. Most of the elements are optional;
 * 				if you
 * 				omit an
 * 				element, corresponding trial data will remain
 * 				unchanged.
 * 			
 * 
 * <p>Java class for AbbreviatedTrialUpdate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbbreviatedTrialUpdate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{gov.nih.nci.pa.webservices.types}clinicalTrialsDotGovTrialID" minOccurs="0"/>
 *         &lt;element name="irbApprovalDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="informedConsentDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="otherDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbbreviatedTrialUpdate", propOrder = {
    "clinicalTrialsDotGovTrialID",
    "irbApprovalDocument",
    "informedConsentDocument",
    "otherDocument"
})
public class AbbreviatedTrialUpdate {

    protected String clinicalTrialsDotGovTrialID;
    protected TrialDocument irbApprovalDocument;
    protected TrialDocument informedConsentDocument;
    protected List<TrialDocument> otherDocument;

    /**
     * 
     * 						If the trial does not currently specify a
     * 						ClinicalTrials.Gov ID
     * 						(a.k.a NCT ID), you can provide one during
     * 						the update.
     * 						If the trial does have a ClinicalTrials.Gov ID already,
     * 						your update
     * 						will not be allowed to change it; an attempt to do so
     * 						will be ignored by CTRP.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalTrialsDotGovTrialID() {
        return clinicalTrialsDotGovTrialID;
    }

    /**
     * Sets the value of the clinicalTrialsDotGovTrialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalTrialsDotGovTrialID(String value) {
        this.clinicalTrialsDotGovTrialID = value;
    }

    /**
     * Gets the value of the irbApprovalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getIrbApprovalDocument() {
        return irbApprovalDocument;
    }

    /**
     * Sets the value of the irbApprovalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setIrbApprovalDocument(TrialDocument value) {
        this.irbApprovalDocument = value;
    }

    /**
     * Gets the value of the informedConsentDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getInformedConsentDocument() {
        return informedConsentDocument;
    }

    /**
     * Sets the value of the informedConsentDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setInformedConsentDocument(TrialDocument value) {
        this.informedConsentDocument = value;
    }

    /**
     * Gets the value of the otherDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrialDocument }
     * 
     * 
     */
    public List<TrialDocument> getOtherDocument() {
        if (otherDocument == null) {
            otherDocument = new ArrayList<TrialDocument>();
        }
        return this.otherDocument;
    }

}
