//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Trial information common to Registration and Amendment
 * 				requests.
 * 			
 * 
 * <p>Java class for BaseTrialInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseTrialInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clinicalTrialsDotGovXmlRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="leadOrgTrialID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{gov.nih.nci.pa.webservices.types}clinicalTrialsDotGovTrialID" minOccurs="0"/>
 *         &lt;element name="otherTrialID" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="title">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase" type="{gov.nih.nci.pa.webservices.types}TrialPhase"/>
 *         &lt;element name="pilot" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accrualDiseaseTerminology" type="{gov.nih.nci.pa.webservices.types}AccrualDiseaseTerminology"/>
 *         &lt;element name="primaryPurpose" type="{gov.nih.nci.pa.webservices.types}PrimaryPurpose"/>
 *         &lt;element name="primaryPurposeOtherDescription" type="{gov.nih.nci.pa.webservices.types}OtherDescription" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="interventionalDesign" type="{gov.nih.nci.pa.webservices.types}InterventionalTrialDesign"/>
 *           &lt;element name="nonInterventionalDesign" type="{gov.nih.nci.pa.webservices.types}NonInterventionalTrialDesign"/>
 *         &lt;/choice>
 *         &lt;element name="leadOrganization" type="{gov.nih.nci.pa.webservices.types}Organization"/>
 *         &lt;element name="pi" type="{gov.nih.nci.pa.webservices.types}Person"/>
 *         &lt;element name="sponsor" type="{gov.nih.nci.pa.webservices.types}Organization" minOccurs="0"/>
 *         &lt;element name="responsibleParty" type="{gov.nih.nci.pa.webservices.types}ResponsibleParty" minOccurs="0"/>
 *         &lt;element name="summary4FundingSponsor" type="{gov.nih.nci.pa.webservices.types}Organization" maxOccurs="unbounded"/>
 *         &lt;element name="programCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fundedByNciGrant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="grant" type="{gov.nih.nci.pa.webservices.types}Grant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trialStatus" type="{gov.nih.nci.pa.webservices.types}TrialStatusCode"/>
 *         &lt;element name="whyStopped" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="160"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trialStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="trialStartDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate"/>
 *         &lt;element name="primaryCompletionDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate"/>
 *         &lt;element name="completionDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate" minOccurs="0"/>
 *         &lt;element name="ind" type="{gov.nih.nci.pa.webservices.types}IND_IDE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ide" type="{gov.nih.nci.pa.webservices.types}IND_IDE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regulatoryInformation" type="{gov.nih.nci.pa.webservices.types}RegulatoryInformation" minOccurs="0"/>
 *         &lt;element name="protocolDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument"/>
 *         &lt;element name="irbApprovalDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument"/>
 *         &lt;element name="participatingSitesDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="informedConsentDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="otherDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseTrialInformation", propOrder = {
    "clinicalTrialsDotGovXmlRequired",
    "leadOrgTrialID",
    "clinicalTrialsDotGovTrialID",
    "otherTrialID",
    "title",
    "phase",
    "pilot",
    "accrualDiseaseTerminology",
    "primaryPurpose",
    "primaryPurposeOtherDescription",
    "interventionalDesign",
    "nonInterventionalDesign",
    "leadOrganization",
    "pi",
    "sponsor",
    "responsibleParty",
    "summary4FundingSponsor",
    "programCode",
    "fundedByNciGrant",
    "grant",
    "trialStatus",
    "whyStopped",
    "trialStatusDate",
    "trialStartDate",
    "primaryCompletionDate",
    "completionDate",
    "ind",
    "ide",
    "regulatoryInformation",
    "protocolDocument",
    "irbApprovalDocument",
    "participatingSitesDocument",
    "informedConsentDocument",
    "otherDocument"
})
@XmlSeeAlso({
    CompleteTrialAmendment.class,
    CompleteTrialRegistration.class
})
public abstract class BaseTrialInformation {

    protected boolean clinicalTrialsDotGovXmlRequired;
    @XmlElement(required = true)
    protected String leadOrgTrialID;
    protected String clinicalTrialsDotGovTrialID;
    protected List<String> otherTrialID;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String phase;
    protected Boolean pilot;
    @XmlElement(required = true)
    protected AccrualDiseaseTerminology accrualDiseaseTerminology;
    @XmlElement(required = true)
    protected PrimaryPurpose primaryPurpose;
    protected String primaryPurposeOtherDescription;
    protected InterventionalTrialDesign interventionalDesign;
    protected NonInterventionalTrialDesign nonInterventionalDesign;
    @XmlElement(required = true)
    protected Organization leadOrganization;
    @XmlElement(required = true)
    protected Person pi;
    protected Organization sponsor;
    protected ResponsibleParty responsibleParty;
    @XmlElement(required = true)
    protected List<Organization> summary4FundingSponsor;
    protected String programCode;
    protected boolean fundedByNciGrant;
    protected List<Grant> grant;
    @XmlElement(required = true)
    protected TrialStatusCode trialStatus;
    protected String whyStopped;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar trialStatusDate;
    @XmlElement(required = true)
    protected ActualOrAnticipatedDate trialStartDate;
    @XmlElement(required = true)
    protected ActualOrAnticipatedDate primaryCompletionDate;
    protected ActualOrAnticipatedDate completionDate;
    protected List<INDIDE> ind;
    protected List<INDIDE> ide;
    protected RegulatoryInformation regulatoryInformation;
    @XmlElement(required = true)
    protected TrialDocument protocolDocument;
    @XmlElement(required = true)
    protected TrialDocument irbApprovalDocument;
    protected TrialDocument participatingSitesDocument;
    protected TrialDocument informedConsentDocument;
    protected List<TrialDocument> otherDocument;

    /**
     * Gets the value of the clinicalTrialsDotGovXmlRequired property.
     * 
     */
    public boolean isClinicalTrialsDotGovXmlRequired() {
        return clinicalTrialsDotGovXmlRequired;
    }

    /**
     * Sets the value of the clinicalTrialsDotGovXmlRequired property.
     * 
     */
    public void setClinicalTrialsDotGovXmlRequired(boolean value) {
        this.clinicalTrialsDotGovXmlRequired = value;
    }

    /**
     * Gets the value of the leadOrgTrialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadOrgTrialID() {
        return leadOrgTrialID;
    }

    /**
     * Sets the value of the leadOrgTrialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadOrgTrialID(String value) {
        this.leadOrgTrialID = value;
    }

    /**
     * Gets the value of the clinicalTrialsDotGovTrialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalTrialsDotGovTrialID() {
        return clinicalTrialsDotGovTrialID;
    }

    /**
     * Sets the value of the clinicalTrialsDotGovTrialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalTrialsDotGovTrialID(String value) {
        this.clinicalTrialsDotGovTrialID = value;
    }

    /**
     * Gets the value of the otherTrialID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherTrialID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherTrialID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherTrialID() {
        if (otherTrialID == null) {
            otherTrialID = new ArrayList<String>();
        }
        return this.otherTrialID;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase(String value) {
        this.phase = value;
    }

    /**
     * Gets the value of the pilot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPilot() {
        return pilot;
    }

    /**
     * Sets the value of the pilot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPilot(Boolean value) {
        this.pilot = value;
    }

    /**
     * Gets the value of the accrualDiseaseTerminology property.
     * 
     * @return
     *     possible object is
     *     {@link AccrualDiseaseTerminology }
     *     
     */
    public AccrualDiseaseTerminology getAccrualDiseaseTerminology() {
        return accrualDiseaseTerminology;
    }

    /**
     * Sets the value of the accrualDiseaseTerminology property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccrualDiseaseTerminology }
     *     
     */
    public void setAccrualDiseaseTerminology(AccrualDiseaseTerminology value) {
        this.accrualDiseaseTerminology = value;
    }

    /**
     * Gets the value of the primaryPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryPurpose }
     *     
     */
    public PrimaryPurpose getPrimaryPurpose() {
        return primaryPurpose;
    }

    /**
     * Sets the value of the primaryPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryPurpose }
     *     
     */
    public void setPrimaryPurpose(PrimaryPurpose value) {
        this.primaryPurpose = value;
    }

    /**
     * Gets the value of the primaryPurposeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryPurposeOtherDescription() {
        return primaryPurposeOtherDescription;
    }

    /**
     * Sets the value of the primaryPurposeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryPurposeOtherDescription(String value) {
        this.primaryPurposeOtherDescription = value;
    }

    /**
     * Gets the value of the interventionalDesign property.
     * 
     * @return
     *     possible object is
     *     {@link InterventionalTrialDesign }
     *     
     */
    public InterventionalTrialDesign getInterventionalDesign() {
        return interventionalDesign;
    }

    /**
     * Sets the value of the interventionalDesign property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterventionalTrialDesign }
     *     
     */
    public void setInterventionalDesign(InterventionalTrialDesign value) {
        this.interventionalDesign = value;
    }

    /**
     * Gets the value of the nonInterventionalDesign property.
     * 
     * @return
     *     possible object is
     *     {@link NonInterventionalTrialDesign }
     *     
     */
    public NonInterventionalTrialDesign getNonInterventionalDesign() {
        return nonInterventionalDesign;
    }

    /**
     * Sets the value of the nonInterventionalDesign property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonInterventionalTrialDesign }
     *     
     */
    public void setNonInterventionalDesign(NonInterventionalTrialDesign value) {
        this.nonInterventionalDesign = value;
    }

    /**
     * Gets the value of the leadOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getLeadOrganization() {
        return leadOrganization;
    }

    /**
     * Sets the value of the leadOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setLeadOrganization(Organization value) {
        this.leadOrganization = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPi() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPi(Person value) {
        this.pi = value;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getSponsor() {
        return sponsor;
    }

    /**
     * Sets the value of the sponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setSponsor(Organization value) {
        this.sponsor = value;
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsibleParty }
     *     
     */
    public ResponsibleParty getResponsibleParty() {
        return responsibleParty;
    }

    /**
     * Sets the value of the responsibleParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsibleParty }
     *     
     */
    public void setResponsibleParty(ResponsibleParty value) {
        this.responsibleParty = value;
    }

    /**
     * Gets the value of the summary4FundingSponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summary4FundingSponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummary4FundingSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Organization }
     * 
     * 
     */
    public List<Organization> getSummary4FundingSponsor() {
        if (summary4FundingSponsor == null) {
            summary4FundingSponsor = new ArrayList<Organization>();
        }
        return this.summary4FundingSponsor;
    }

    /**
     * Gets the value of the programCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCode() {
        return programCode;
    }

    /**
     * Sets the value of the programCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCode(String value) {
        this.programCode = value;
    }

    /**
     * Gets the value of the fundedByNciGrant property.
     * 
     */
    public boolean isFundedByNciGrant() {
        return fundedByNciGrant;
    }

    /**
     * Sets the value of the fundedByNciGrant property.
     * 
     */
    public void setFundedByNciGrant(boolean value) {
        this.fundedByNciGrant = value;
    }

    /**
     * Gets the value of the grant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grant }
     * 
     * 
     */
    public List<Grant> getGrant() {
        if (grant == null) {
            grant = new ArrayList<Grant>();
        }
        return this.grant;
    }

    /**
     * Gets the value of the trialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TrialStatusCode }
     *     
     */
    public TrialStatusCode getTrialStatus() {
        return trialStatus;
    }

    /**
     * Sets the value of the trialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialStatusCode }
     *     
     */
    public void setTrialStatus(TrialStatusCode value) {
        this.trialStatus = value;
    }

    /**
     * Gets the value of the whyStopped property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhyStopped() {
        return whyStopped;
    }

    /**
     * Sets the value of the whyStopped property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhyStopped(String value) {
        this.whyStopped = value;
    }

    /**
     * Gets the value of the trialStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrialStatusDate() {
        return trialStatusDate;
    }

    /**
     * Sets the value of the trialStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrialStatusDate(XMLGregorianCalendar value) {
        this.trialStatusDate = value;
    }

    /**
     * Gets the value of the trialStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getTrialStartDate() {
        return trialStartDate;
    }

    /**
     * Sets the value of the trialStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setTrialStartDate(ActualOrAnticipatedDate value) {
        this.trialStartDate = value;
    }

    /**
     * Gets the value of the primaryCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getPrimaryCompletionDate() {
        return primaryCompletionDate;
    }

    /**
     * Sets the value of the primaryCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setPrimaryCompletionDate(ActualOrAnticipatedDate value) {
        this.primaryCompletionDate = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setCompletionDate(ActualOrAnticipatedDate value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the ind property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ind property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INDIDE }
     * 
     * 
     */
    public List<INDIDE> getInd() {
        if (ind == null) {
            ind = new ArrayList<INDIDE>();
        }
        return this.ind;
    }

    /**
     * Gets the value of the ide property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ide property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIde().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INDIDE }
     * 
     * 
     */
    public List<INDIDE> getIde() {
        if (ide == null) {
            ide = new ArrayList<INDIDE>();
        }
        return this.ide;
    }

    /**
     * Gets the value of the regulatoryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RegulatoryInformation }
     *     
     */
    public RegulatoryInformation getRegulatoryInformation() {
        return regulatoryInformation;
    }

    /**
     * Sets the value of the regulatoryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulatoryInformation }
     *     
     */
    public void setRegulatoryInformation(RegulatoryInformation value) {
        this.regulatoryInformation = value;
    }

    /**
     * Gets the value of the protocolDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getProtocolDocument() {
        return protocolDocument;
    }

    /**
     * Sets the value of the protocolDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setProtocolDocument(TrialDocument value) {
        this.protocolDocument = value;
    }

    /**
     * Gets the value of the irbApprovalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getIrbApprovalDocument() {
        return irbApprovalDocument;
    }

    /**
     * Sets the value of the irbApprovalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setIrbApprovalDocument(TrialDocument value) {
        this.irbApprovalDocument = value;
    }

    /**
     * Gets the value of the participatingSitesDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getParticipatingSitesDocument() {
        return participatingSitesDocument;
    }

    /**
     * Sets the value of the participatingSitesDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setParticipatingSitesDocument(TrialDocument value) {
        this.participatingSitesDocument = value;
    }

    /**
     * Gets the value of the informedConsentDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getInformedConsentDocument() {
        return informedConsentDocument;
    }

    /**
     * Sets the value of the informedConsentDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setInformedConsentDocument(TrialDocument value) {
        this.informedConsentDocument = value;
    }

    /**
     * Gets the value of the otherDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrialDocument }
     * 
     * 
     */
    public List<TrialDocument> getOtherDocument() {
        if (otherDocument == null) {
            otherDocument = new ArrayList<TrialDocument>();
        }
        return this.otherDocument;
    }

}
