//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A request to update a Complete trial in CTRP. An
 * 				update permits trial owners to change a limited set
 * 				of data element
 * 				of the trial. Most of the elements are optional; if you omit an
 * 				element, corresponding trial data will remain unchanged.
 * 			
 * 
 * <p>Java class for CompleteTrialUpdate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompleteTrialUpdate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{gov.nih.nci.pa.webservices.types}clinicalTrialsDotGovTrialID" minOccurs="0"/>
 *         &lt;element name="otherTrialID" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accrualDiseaseTerminology" type="{gov.nih.nci.pa.webservices.types}AccrualDiseaseTerminology" minOccurs="0"/>
 *         &lt;element name="grant" type="{gov.nih.nci.pa.webservices.types}Grant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trialStatus" type="{gov.nih.nci.pa.webservices.types}TrialStatusCode" minOccurs="0"/>
 *         &lt;element name="whyStopped" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="160"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trialStatusDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="trialStartDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate" minOccurs="0"/>
 *         &lt;element name="primaryCompletionDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate" minOccurs="0"/>
 *         &lt;element name="completionDate" type="{gov.nih.nci.pa.webservices.types}ActualOrAnticipatedDate" minOccurs="0"/>
 *         &lt;element name="protocolDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="irbApprovalDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="participatingSitesDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="informedConsentDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="otherDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompleteTrialUpdate", propOrder = {
    "clinicalTrialsDotGovTrialID",
    "otherTrialID",
    "accrualDiseaseTerminology",
    "grant",
    "trialStatus",
    "whyStopped",
    "trialStatusDate",
    "trialStartDate",
    "primaryCompletionDate",
    "completionDate",
    "protocolDocument",
    "irbApprovalDocument",
    "participatingSitesDocument",
    "informedConsentDocument",
    "otherDocument"
})
public class CompleteTrialUpdate {

    protected String clinicalTrialsDotGovTrialID;
    protected List<String> otherTrialID;
    protected AccrualDiseaseTerminology accrualDiseaseTerminology;
    protected List<Grant> grant;
    protected TrialStatusCode trialStatus;
    protected String whyStopped;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar trialStatusDate;
    protected ActualOrAnticipatedDate trialStartDate;
    protected ActualOrAnticipatedDate primaryCompletionDate;
    protected ActualOrAnticipatedDate completionDate;
    protected TrialDocument protocolDocument;
    protected TrialDocument irbApprovalDocument;
    protected TrialDocument participatingSitesDocument;
    protected TrialDocument informedConsentDocument;
    protected List<TrialDocument> otherDocument;

    /**
     * 
     * 						If the trial does not currently specify a
     * 						ClinicalTrials.Gov ID
     * 						(a.k.a NCT ID), you can provide one during
     * 						the update.
     * 						If the trial does have a ClinicalTrials.Gov ID already,
     * 						your update
     * 						will not be allowed to change it; an attempt to do so
     * 						will be ignored by CTRP.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalTrialsDotGovTrialID() {
        return clinicalTrialsDotGovTrialID;
    }

    /**
     * Sets the value of the clinicalTrialsDotGovTrialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalTrialsDotGovTrialID(String value) {
        this.clinicalTrialsDotGovTrialID = value;
    }

    /**
     * Gets the value of the otherTrialID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherTrialID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherTrialID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherTrialID() {
        if (otherTrialID == null) {
            otherTrialID = new ArrayList<String>();
        }
        return this.otherTrialID;
    }

    /**
     * Gets the value of the accrualDiseaseTerminology property.
     * 
     * @return
     *     possible object is
     *     {@link AccrualDiseaseTerminology }
     *     
     */
    public AccrualDiseaseTerminology getAccrualDiseaseTerminology() {
        return accrualDiseaseTerminology;
    }

    /**
     * Sets the value of the accrualDiseaseTerminology property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccrualDiseaseTerminology }
     *     
     */
    public void setAccrualDiseaseTerminology(AccrualDiseaseTerminology value) {
        this.accrualDiseaseTerminology = value;
    }

    /**
     * Gets the value of the grant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grant }
     * 
     * 
     */
    public List<Grant> getGrant() {
        if (grant == null) {
            grant = new ArrayList<Grant>();
        }
        return this.grant;
    }

    /**
     * Gets the value of the trialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TrialStatusCode }
     *     
     */
    public TrialStatusCode getTrialStatus() {
        return trialStatus;
    }

    /**
     * Sets the value of the trialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialStatusCode }
     *     
     */
    public void setTrialStatus(TrialStatusCode value) {
        this.trialStatus = value;
    }

    /**
     * Gets the value of the whyStopped property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhyStopped() {
        return whyStopped;
    }

    /**
     * Sets the value of the whyStopped property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhyStopped(String value) {
        this.whyStopped = value;
    }

    /**
     * Gets the value of the trialStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrialStatusDate() {
        return trialStatusDate;
    }

    /**
     * Sets the value of the trialStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrialStatusDate(XMLGregorianCalendar value) {
        this.trialStatusDate = value;
    }

    /**
     * Gets the value of the trialStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getTrialStartDate() {
        return trialStartDate;
    }

    /**
     * Sets the value of the trialStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setTrialStartDate(ActualOrAnticipatedDate value) {
        this.trialStartDate = value;
    }

    /**
     * Gets the value of the primaryCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getPrimaryCompletionDate() {
        return primaryCompletionDate;
    }

    /**
     * Sets the value of the primaryCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setPrimaryCompletionDate(ActualOrAnticipatedDate value) {
        this.primaryCompletionDate = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public ActualOrAnticipatedDate getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOrAnticipatedDate }
     *     
     */
    public void setCompletionDate(ActualOrAnticipatedDate value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the protocolDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getProtocolDocument() {
        return protocolDocument;
    }

    /**
     * Sets the value of the protocolDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setProtocolDocument(TrialDocument value) {
        this.protocolDocument = value;
    }

    /**
     * Gets the value of the irbApprovalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getIrbApprovalDocument() {
        return irbApprovalDocument;
    }

    /**
     * Sets the value of the irbApprovalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setIrbApprovalDocument(TrialDocument value) {
        this.irbApprovalDocument = value;
    }

    /**
     * Gets the value of the participatingSitesDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getParticipatingSitesDocument() {
        return participatingSitesDocument;
    }

    /**
     * Sets the value of the participatingSitesDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setParticipatingSitesDocument(TrialDocument value) {
        this.participatingSitesDocument = value;
    }

    /**
     * Gets the value of the informedConsentDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getInformedConsentDocument() {
        return informedConsentDocument;
    }

    /**
     * Sets the value of the informedConsentDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setInformedConsentDocument(TrialDocument value) {
        this.informedConsentDocument = value;
    }

    /**
     * Gets the value of the otherDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrialDocument }
     * 
     * 
     */
    public List<TrialDocument> getOtherDocument() {
        if (otherDocument == null) {
            otherDocument = new ArrayList<TrialDocument>();
        }
        return this.otherDocument;
    }

}
