//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A request to amend a Complete trial in CTRP.
 * 			
 * 
 * <p>Java class for CompleteTrialAmendment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompleteTrialAmendment">
 *   &lt;complexContent>
 *     &lt;extension base="{gov.nih.nci.pa.webservices.types}BaseTrialInformation">
 *       &lt;sequence>
 *         &lt;element name="amendmentNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amendmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ctepIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dcpIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="changeMemoDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *         &lt;element name="protocolHighlightDocument" type="{gov.nih.nci.pa.webservices.types}TrialDocument" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompleteTrialAmendment", propOrder = {
    "amendmentNumber",
    "amendmentDate",
    "ctepIdentifier",
    "dcpIdentifier",
    "changeMemoDocument",
    "protocolHighlightDocument"
})
public class CompleteTrialAmendment
    extends BaseTrialInformation
{

    protected String amendmentNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar amendmentDate;
    protected String ctepIdentifier;
    protected String dcpIdentifier;
    protected TrialDocument changeMemoDocument;
    protected TrialDocument protocolHighlightDocument;

    /**
     * Gets the value of the amendmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendmentNumber() {
        return amendmentNumber;
    }

    /**
     * Sets the value of the amendmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendmentNumber(String value) {
        this.amendmentNumber = value;
    }

    /**
     * Gets the value of the amendmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAmendmentDate() {
        return amendmentDate;
    }

    /**
     * Sets the value of the amendmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAmendmentDate(XMLGregorianCalendar value) {
        this.amendmentDate = value;
    }

    /**
     * Gets the value of the ctepIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtepIdentifier() {
        return ctepIdentifier;
    }

    /**
     * Sets the value of the ctepIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtepIdentifier(String value) {
        this.ctepIdentifier = value;
    }

    /**
     * Gets the value of the dcpIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDcpIdentifier() {
        return dcpIdentifier;
    }

    /**
     * Sets the value of the dcpIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDcpIdentifier(String value) {
        this.dcpIdentifier = value;
    }

    /**
     * Gets the value of the changeMemoDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getChangeMemoDocument() {
        return changeMemoDocument;
    }

    /**
     * Sets the value of the changeMemoDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setChangeMemoDocument(TrialDocument value) {
        this.changeMemoDocument = value;
    }

    /**
     * Gets the value of the protocolHighlightDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TrialDocument }
     *     
     */
    public TrialDocument getProtocolHighlightDocument() {
        return protocolHighlightDocument;
    }

    /**
     * Sets the value of the protocolHighlightDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialDocument }
     *     
     */
    public void setProtocolHighlightDocument(TrialDocument value) {
        this.protocolHighlightDocument = value;
    }

}
