//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Captures information about an Investigational New Drug
 * 				(IND)
 * 				application or an Investigational
 * 				Device Exemption (IDE) used on
 * 				the trial.
 * 			
 * 
 * <p>Java class for IND_IDE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IND_IDE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grantor" type="{gov.nih.nci.pa.webservices.types}GrantorCode"/>
 *         &lt;element name="holderType" type="{gov.nih.nci.pa.webservices.types}HolderType"/>
 *         &lt;element name="nihInstitution" type="{gov.nih.nci.pa.webservices.types}NihInstitutionCode" minOccurs="0"/>
 *         &lt;element name="nciDivisionProgramCode" type="{gov.nih.nci.pa.webservices.types}NciDivisionProgramCode" minOccurs="0"/>
 *         &lt;element name="expandedAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="expandedAccessType" type="{gov.nih.nci.pa.webservices.types}ExpandedAccessType" minOccurs="0"/>
 *         &lt;element name="exempt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IND_IDE", propOrder = {
    "number",
    "grantor",
    "holderType",
    "nihInstitution",
    "nciDivisionProgramCode",
    "expandedAccess",
    "expandedAccessType",
    "exempt"
})
public class INDIDE {

    @XmlElement(required = true)
    protected String number;
    @XmlElement(required = true)
    protected GrantorCode grantor;
    @XmlElement(required = true)
    protected HolderType holderType;
    protected NihInstitutionCode nihInstitution;
    protected NciDivisionProgramCode nciDivisionProgramCode;
    protected boolean expandedAccess;
    protected ExpandedAccessType expandedAccessType;
    protected boolean exempt;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the grantor property.
     * 
     * @return
     *     possible object is
     *     {@link GrantorCode }
     *     
     */
    public GrantorCode getGrantor() {
        return grantor;
    }

    /**
     * Sets the value of the grantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantorCode }
     *     
     */
    public void setGrantor(GrantorCode value) {
        this.grantor = value;
    }

    /**
     * Gets the value of the holderType property.
     * 
     * @return
     *     possible object is
     *     {@link HolderType }
     *     
     */
    public HolderType getHolderType() {
        return holderType;
    }

    /**
     * Sets the value of the holderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HolderType }
     *     
     */
    public void setHolderType(HolderType value) {
        this.holderType = value;
    }

    /**
     * Gets the value of the nihInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link NihInstitutionCode }
     *     
     */
    public NihInstitutionCode getNihInstitution() {
        return nihInstitution;
    }

    /**
     * Sets the value of the nihInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link NihInstitutionCode }
     *     
     */
    public void setNihInstitution(NihInstitutionCode value) {
        this.nihInstitution = value;
    }

    /**
     * Gets the value of the nciDivisionProgramCode property.
     * 
     * @return
     *     possible object is
     *     {@link NciDivisionProgramCode }
     *     
     */
    public NciDivisionProgramCode getNciDivisionProgramCode() {
        return nciDivisionProgramCode;
    }

    /**
     * Sets the value of the nciDivisionProgramCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NciDivisionProgramCode }
     *     
     */
    public void setNciDivisionProgramCode(NciDivisionProgramCode value) {
        this.nciDivisionProgramCode = value;
    }

    /**
     * Gets the value of the expandedAccess property.
     * 
     */
    public boolean isExpandedAccess() {
        return expandedAccess;
    }

    /**
     * Sets the value of the expandedAccess property.
     * 
     */
    public void setExpandedAccess(boolean value) {
        this.expandedAccess = value;
    }

    /**
     * Gets the value of the expandedAccessType property.
     * 
     * @return
     *     possible object is
     *     {@link ExpandedAccessType }
     *     
     */
    public ExpandedAccessType getExpandedAccessType() {
        return expandedAccessType;
    }

    /**
     * Sets the value of the expandedAccessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpandedAccessType }
     *     
     */
    public void setExpandedAccessType(ExpandedAccessType value) {
        this.expandedAccessType = value;
    }

    /**
     * Gets the value of the exempt property.
     * 
     */
    public boolean isExempt() {
        return exempt;
    }

    /**
     * Sets the value of the exempt property.
     * 
     */
    public void setExempt(boolean value) {
        this.exempt = value;
    }

}
