//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Design details of an Interventional trial.
 * 			
 * 
 * <p>Java class for InterventionalTrialDesign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterventionalTrialDesign">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="secondaryPurpose" type="{gov.nih.nci.pa.webservices.types}SecondaryPurpose" minOccurs="0"/>
 *         &lt;element name="secondaryPurposeOtherDescription" type="{gov.nih.nci.pa.webservices.types}OtherDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterventionalTrialDesign", propOrder = {
    "secondaryPurpose",
    "secondaryPurposeOtherDescription"
})
public class InterventionalTrialDesign {

    protected SecondaryPurpose secondaryPurpose;
    protected String secondaryPurposeOtherDescription;

    /**
     * Gets the value of the secondaryPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link SecondaryPurpose }
     *     
     */
    public SecondaryPurpose getSecondaryPurpose() {
        return secondaryPurpose;
    }

    /**
     * Sets the value of the secondaryPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondaryPurpose }
     *     
     */
    public void setSecondaryPurpose(SecondaryPurpose value) {
        this.secondaryPurpose = value;
    }

    /**
     * Gets the value of the secondaryPurposeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryPurposeOtherDescription() {
        return secondaryPurposeOtherDescription;
    }

    /**
     * Sets the value of the secondaryPurposeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryPurposeOtherDescription(String value) {
        this.secondaryPurposeOtherDescription = value;
    }

}
