//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Design details of a Non-Interventional trial.
 * 			
 * 
 * <p>Java class for NonInterventionalTrialDesign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonInterventionalTrialDesign">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trialType" type="{gov.nih.nci.pa.webservices.types}NonInterventionalTrialType"/>
 *         &lt;element name="studyModelCode" type="{gov.nih.nci.pa.webservices.types}StudyModelCode"/>
 *         &lt;element name="studyModelCodeOtherDescription" type="{gov.nih.nci.pa.webservices.types}OtherDescription" minOccurs="0"/>
 *         &lt;element name="timePerspectiveCode" type="{gov.nih.nci.pa.webservices.types}TimePerspectiveCode"/>
 *         &lt;element name="timePerspectiveCodeOtherDescription" type="{gov.nih.nci.pa.webservices.types}OtherDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonInterventionalTrialDesign", propOrder = {
    "trialType",
    "studyModelCode",
    "studyModelCodeOtherDescription",
    "timePerspectiveCode",
    "timePerspectiveCodeOtherDescription"
})
public class NonInterventionalTrialDesign {

    @XmlElement(required = true)
    protected NonInterventionalTrialType trialType;
    @XmlElement(required = true)
    protected StudyModelCode studyModelCode;
    protected String studyModelCodeOtherDescription;
    @XmlElement(required = true)
    protected TimePerspectiveCode timePerspectiveCode;
    protected String timePerspectiveCodeOtherDescription;

    /**
     * Gets the value of the trialType property.
     * 
     * @return
     *     possible object is
     *     {@link NonInterventionalTrialType }
     *     
     */
    public NonInterventionalTrialType getTrialType() {
        return trialType;
    }

    /**
     * Sets the value of the trialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonInterventionalTrialType }
     *     
     */
    public void setTrialType(NonInterventionalTrialType value) {
        this.trialType = value;
    }

    /**
     * Gets the value of the studyModelCode property.
     * 
     * @return
     *     possible object is
     *     {@link StudyModelCode }
     *     
     */
    public StudyModelCode getStudyModelCode() {
        return studyModelCode;
    }

    /**
     * Sets the value of the studyModelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyModelCode }
     *     
     */
    public void setStudyModelCode(StudyModelCode value) {
        this.studyModelCode = value;
    }

    /**
     * Gets the value of the studyModelCodeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyModelCodeOtherDescription() {
        return studyModelCodeOtherDescription;
    }

    /**
     * Sets the value of the studyModelCodeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyModelCodeOtherDescription(String value) {
        this.studyModelCodeOtherDescription = value;
    }

    /**
     * Gets the value of the timePerspectiveCode property.
     * 
     * @return
     *     possible object is
     *     {@link TimePerspectiveCode }
     *     
     */
    public TimePerspectiveCode getTimePerspectiveCode() {
        return timePerspectiveCode;
    }

    /**
     * Sets the value of the timePerspectiveCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePerspectiveCode }
     *     
     */
    public void setTimePerspectiveCode(TimePerspectiveCode value) {
        this.timePerspectiveCode = value;
    }

    /**
     * Gets the value of the timePerspectiveCodeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimePerspectiveCodeOtherDescription() {
        return timePerspectiveCodeOtherDescription;
    }

    /**
     * Sets the value of the timePerspectiveCodeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimePerspectiveCodeOtherDescription(String value) {
        this.timePerspectiveCodeOtherDescription = value;
    }

}
