//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonInterventionalTrialType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NonInterventionalTrialType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Observational"/>
 *     &lt;enumeration value="Ancillary-Correlative"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NonInterventionalTrialType")
@XmlEnum
public enum NonInterventionalTrialType {

    @XmlEnumValue("Observational")
    OBSERVATIONAL("Observational"),
    @XmlEnumValue("Ancillary-Correlative")
    ANCILLARY_CORRELATIVE("Ancillary-Correlative");
    private final String value;

    NonInterventionalTrialType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NonInterventionalTrialType fromValue(String v) {
        for (NonInterventionalTrialType c: NonInterventionalTrialType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
