//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.nci.pa.webservices.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TrialRegistrationConfirmation_QNAME = new QName("gov.nih.nci.pa.webservices.types", "TrialRegistrationConfirmation");
    private final static QName _CompleteTrialAmendment_QNAME = new QName("gov.nih.nci.pa.webservices.types", "CompleteTrialAmendment");
    private final static QName _ParticipatingSite_QNAME = new QName("gov.nih.nci.pa.webservices.types", "ParticipatingSite");
    private final static QName _ParticipatingSiteUpdate_QNAME = new QName("gov.nih.nci.pa.webservices.types", "ParticipatingSiteUpdate");
    private final static QName _ClinicalTrialsDotGovTrialID_QNAME = new QName("gov.nih.nci.pa.webservices.types", "clinicalTrialsDotGovTrialID");
    private final static QName _CompleteTrialUpdate_QNAME = new QName("gov.nih.nci.pa.webservices.types", "CompleteTrialUpdate");
    private final static QName _AbbreviatedTrialUpdate_QNAME = new QName("gov.nih.nci.pa.webservices.types", "AbbreviatedTrialUpdate");
    private final static QName _CompleteTrialRegistration_QNAME = new QName("gov.nih.nci.pa.webservices.types", "CompleteTrialRegistration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.nci.pa.webservices.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sites }
     * 
     */
    public Sites createSites() {
        return new Sites();
    }

    /**
     * Create an instance of {@link ParticipatingSite }
     * 
     */
    public ParticipatingSite createParticipatingSite() {
        return new ParticipatingSite();
    }

    /**
     * Create an instance of {@link CompleteTrialAmendment }
     * 
     */
    public CompleteTrialAmendment createCompleteTrialAmendment() {
        return new CompleteTrialAmendment();
    }

    /**
     * Create an instance of {@link TrialRegistrationConfirmation }
     * 
     */
    public TrialRegistrationConfirmation createTrialRegistrationConfirmation() {
        return new TrialRegistrationConfirmation();
    }

    /**
     * Create an instance of {@link ParticipatingSiteUpdate }
     * 
     */
    public ParticipatingSiteUpdate createParticipatingSiteUpdate() {
        return new ParticipatingSiteUpdate();
    }

    /**
     * Create an instance of {@link CompleteTrialRegistration }
     * 
     */
    public CompleteTrialRegistration createCompleteTrialRegistration() {
        return new CompleteTrialRegistration();
    }

    /**
     * Create an instance of {@link AbbreviatedTrialUpdate }
     * 
     */
    public AbbreviatedTrialUpdate createAbbreviatedTrialUpdate() {
        return new AbbreviatedTrialUpdate();
    }

    /**
     * Create an instance of {@link CompleteTrialUpdate }
     * 
     */
    public CompleteTrialUpdate createCompleteTrialUpdate() {
        return new CompleteTrialUpdate();
    }

    /**
     * Create an instance of {@link TrialDocument }
     * 
     */
    public TrialDocument createTrialDocument() {
        return new TrialDocument();
    }

    /**
     * Create an instance of {@link ActualOrAnticipatedDate }
     * 
     */
    public ActualOrAnticipatedDate createActualOrAnticipatedDate() {
        return new ActualOrAnticipatedDate();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link NonInterventionalTrialDesign }
     * 
     */
    public NonInterventionalTrialDesign createNonInterventionalTrialDesign() {
        return new NonInterventionalTrialDesign();
    }

    /**
     * Create an instance of {@link Grant }
     * 
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link INDIDE }
     * 
     */
    public INDIDE createINDIDE() {
        return new INDIDE();
    }

    /**
     * Create an instance of {@link InterventionalTrialDesign }
     * 
     */
    public InterventionalTrialDesign createInterventionalTrialDesign() {
        return new InterventionalTrialDesign();
    }

    /**
     * Create an instance of {@link ResponsibleParty }
     * 
     */
    public ResponsibleParty createResponsibleParty() {
        return new ResponsibleParty();
    }

    /**
     * Create an instance of {@link OrganizationOrPersonID }
     * 
     */
    public OrganizationOrPersonID createOrganizationOrPersonID() {
        return new OrganizationOrPersonID();
    }

    /**
     * Create an instance of {@link RegulatoryInformation }
     * 
     */
    public RegulatoryInformation createRegulatoryInformation() {
        return new RegulatoryInformation();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link gov.nih.nci.pa.webservices.types.BaseParticipatingSite.Investigator }
     * 
     */
    public gov.nih.nci.pa.webservices.types.BaseParticipatingSite.Investigator createBaseParticipatingSiteInvestigator() {
        return new gov.nih.nci.pa.webservices.types.BaseParticipatingSite.Investigator();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrialRegistrationConfirmation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "TrialRegistrationConfirmation")
    public JAXBElement<TrialRegistrationConfirmation> createTrialRegistrationConfirmation(TrialRegistrationConfirmation value) {
        return new JAXBElement<TrialRegistrationConfirmation>(_TrialRegistrationConfirmation_QNAME, TrialRegistrationConfirmation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteTrialAmendment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "CompleteTrialAmendment")
    public JAXBElement<CompleteTrialAmendment> createCompleteTrialAmendment(CompleteTrialAmendment value) {
        return new JAXBElement<CompleteTrialAmendment>(_CompleteTrialAmendment_QNAME, CompleteTrialAmendment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipatingSite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "ParticipatingSite")
    public JAXBElement<ParticipatingSite> createParticipatingSite(ParticipatingSite value) {
        return new JAXBElement<ParticipatingSite>(_ParticipatingSite_QNAME, ParticipatingSite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipatingSiteUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "ParticipatingSiteUpdate")
    public JAXBElement<ParticipatingSiteUpdate> createParticipatingSiteUpdate(ParticipatingSiteUpdate value) {
        return new JAXBElement<ParticipatingSiteUpdate>(_ParticipatingSiteUpdate_QNAME, ParticipatingSiteUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "clinicalTrialsDotGovTrialID")
    public JAXBElement<String> createClinicalTrialsDotGovTrialID(String value) {
        return new JAXBElement<String>(_ClinicalTrialsDotGovTrialID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteTrialUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "CompleteTrialUpdate")
    public JAXBElement<CompleteTrialUpdate> createCompleteTrialUpdate(CompleteTrialUpdate value) {
        return new JAXBElement<CompleteTrialUpdate>(_CompleteTrialUpdate_QNAME, CompleteTrialUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbbreviatedTrialUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "AbbreviatedTrialUpdate")
    public JAXBElement<AbbreviatedTrialUpdate> createAbbreviatedTrialUpdate(AbbreviatedTrialUpdate value) {
        return new JAXBElement<AbbreviatedTrialUpdate>(_AbbreviatedTrialUpdate_QNAME, AbbreviatedTrialUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteTrialRegistration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov.nih.nci.pa.webservices.types", name = "CompleteTrialRegistration")
    public JAXBElement<CompleteTrialRegistration> createCompleteTrialRegistration(CompleteTrialRegistration value) {
        return new JAXBElement<CompleteTrialRegistration>(_CompleteTrialRegistration_QNAME, CompleteTrialRegistration.class, null, value);
    }

}
