//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Every Organization or Person in CTRP normally can be
 * 				uniquely identified
 * 				by either a numeric PO ID (preferred)
 * 				or a CTEP
 * 				ID. In most cases when you need to refer to an existing Organization
 * 				or Person, you can use either type of identifier.
 * 			
 * 
 * <p>Java class for OrganizationOrPersonID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationOrPersonID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="poID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ctepID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationOrPersonID", propOrder = {
    "poID",
    "ctepID"
})
public class OrganizationOrPersonID {

    protected Long poID;
    protected String ctepID;

    /**
     * Gets the value of the poID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPoID() {
        return poID;
    }

    /**
     * Sets the value of the poID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPoID(Long value) {
        this.poID = value;
    }

    /**
     * Gets the value of the ctepID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtepID() {
        return ctepID;
    }

    /**
     * Sets the value of the ctepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtepID(String value) {
        this.ctepID = value;
    }

}
