//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents information about an Organization that
 * 				plays a role (Lead Organization, Sponsor, etc) on a
 * 				trial. Every
 * 				organization ultimately must exist in NCI PO (Curation) Tool. If it
 * 				does not,
 * 				it has to be created in PO before a trial can be
 * 				registered. If you know PO ID or CTEP ID of an organization that
 * 				already exists, please use that in order
 * 				to avoid creation of
 * 				duplicates. It is strongly recommended that you exercise NCI PO Web
 * 				Services separately to search for the organization you need
 * 				and
 * 				obtain a PO ID prior to invoking CTRP Trial Registration or
 * 				Participating Site services. However, if you intend to create a new
 * 				organization, please provide organization
 * 				information here.
 * 			
 * 
 * <p>Java class for Organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="existingOrganization" type="{gov.nih.nci.pa.webservices.types}OrganizationOrPersonID"/>
 *           &lt;element name="newOrganization" type="{gov.nih.nci.po.webservices.types.trimmed}Organization"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organization", propOrder = {
    "existingOrganization",
    "newOrganization"
})
public class Organization {

    protected OrganizationOrPersonID existingOrganization;
    protected gov.nih.nci.po.webservices.types.Organization newOrganization;

    /**
     * Gets the value of the existingOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationOrPersonID }
     *     
     */
    public OrganizationOrPersonID getExistingOrganization() {
        return existingOrganization;
    }

    /**
     * Sets the value of the existingOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationOrPersonID }
     *     
     */
    public void setExistingOrganization(OrganizationOrPersonID value) {
        this.existingOrganization = value;
    }

    /**
     * Gets the value of the newOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link gov.nih.nci.po.webservices.types.Organization }
     *     
     */
    public gov.nih.nci.po.webservices.types.Organization getNewOrganization() {
        return newOrganization;
    }

    /**
     * Sets the value of the newOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.nih.nci.po.webservices.types.Organization }
     *     
     */
    public void setNewOrganization(gov.nih.nci.po.webservices.types.Organization value) {
        this.newOrganization = value;
    }

}
