//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents a new or existing participating site on a
 * 				trial: this
 * 				includes organization information.
 * 			
 * 
 * <p>Java class for ParticipatingSite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParticipatingSite">
 *   &lt;complexContent>
 *     &lt;extension base="{gov.nih.nci.pa.webservices.types}BaseParticipatingSite">
 *       &lt;sequence>
 *         &lt;element name="organization" type="{gov.nih.nci.pa.webservices.types}Organization"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="ParticipatingSite")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParticipatingSite", propOrder = {
    "organization"
})
public class ParticipatingSite
    extends BaseParticipatingSite
{

    @XmlElement(required = true)
    protected Organization organization;

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

}
