//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents an update to a participating site. Since an
 * 				update to a site cannot change the organization, this type excludes
 * 				the organization element.
 * 			
 * 
 * <p>Java class for ParticipatingSiteUpdate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParticipatingSiteUpdate">
 *   &lt;complexContent>
 *     &lt;extension base="{gov.nih.nci.pa.webservices.types}BaseParticipatingSite">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="ParticipatingSiteUpdate")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParticipatingSiteUpdate")
public class ParticipatingSiteUpdate
    extends BaseParticipatingSite
{


}
