//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents information about a Person that
 * 				plays a role
 * 				(Principal Investigator, etc) on a
 * 				trial. Every
 * 				Person ultimately must
 * 				exist in NCI PO (Curation) Tool. If it
 * 				does not,
 * 				it has to be created
 * 				in PO before a trial can be
 * 				registered. If you know PO ID or CTEP ID
 * 				of a Person that
 * 				already exists, please use that in order
 * 				to avoid
 * 				creation of
 * 				duplicates. It is strongly recommended that you exercise
 * 				NCI PO Web
 * 				Services separately to search for the Person you need
 * 				and
 * 				obtain a PO ID prior to invoking CTRP Trial Registration or
 * 				Participating Site services. However, if you intend to create a new
 * 				Person, please provide person
 * 				information here.
 * 			
 * 
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="existingPerson" type="{gov.nih.nci.pa.webservices.types}OrganizationOrPersonID"/>
 *           &lt;element name="newPerson" type="{gov.nih.nci.po.webservices.types.trimmed}Person"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "existingPerson",
    "newPerson"
})
public class Person {

    protected OrganizationOrPersonID existingPerson;
    protected gov.nih.nci.po.webservices.types.Person newPerson;

    /**
     * Gets the value of the existingPerson property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationOrPersonID }
     *     
     */
    public OrganizationOrPersonID getExistingPerson() {
        return existingPerson;
    }

    /**
     * Sets the value of the existingPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationOrPersonID }
     *     
     */
    public void setExistingPerson(OrganizationOrPersonID value) {
        this.existingPerson = value;
    }

    /**
     * Gets the value of the newPerson property.
     * 
     * @return
     *     possible object is
     *     {@link gov.nih.nci.po.webservices.types.Person }
     *     
     */
    public gov.nih.nci.po.webservices.types.Person getNewPerson() {
        return newPerson;
    }

    /**
     * Sets the value of the newPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.nih.nci.po.webservices.types.Person }
     *     
     */
    public void setNewPerson(gov.nih.nci.po.webservices.types.Person value) {
        this.newPerson = value;
    }

}
