//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecruitmentStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecruitmentStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="In Review"/>
 *     &lt;enumeration value="Approved"/>
 *     &lt;enumeration value="Active"/>
 *     &lt;enumeration value="Enrolling by Invitation"/>
 *     &lt;enumeration value="Closed to Accrual"/>
 *     &lt;enumeration value="Closed to Accrual and Intervention"/>
 *     &lt;enumeration value="Temporarily Closed to Accrual"/>
 *     &lt;enumeration value="Temporarily Closed to Accrual and Intervention"/>
 *     &lt;enumeration value="Withdrawn"/>
 *     &lt;enumeration value="Administratively Complete"/>
 *     &lt;enumeration value="Completed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecruitmentStatus")
@XmlEnum
public enum RecruitmentStatus {

    @XmlEnumValue("In Review")
    IN_REVIEW("In Review"),
    @XmlEnumValue("Approved")
    APPROVED("Approved"),
    @XmlEnumValue("Active")
    ACTIVE("Active"),
    @XmlEnumValue("Enrolling by Invitation")
    ENROLLING_BY_INVITATION("Enrolling by Invitation"),
    @XmlEnumValue("Closed to Accrual")
    CLOSED_TO_ACCRUAL("Closed to Accrual"),
    @XmlEnumValue("Closed to Accrual and Intervention")
    CLOSED_TO_ACCRUAL_AND_INTERVENTION("Closed to Accrual and Intervention"),
    @XmlEnumValue("Temporarily Closed to Accrual")
    TEMPORARILY_CLOSED_TO_ACCRUAL("Temporarily Closed to Accrual"),
    @XmlEnumValue("Temporarily Closed to Accrual and Intervention")
    TEMPORARILY_CLOSED_TO_ACCRUAL_AND_INTERVENTION("Temporarily Closed to Accrual and Intervention"),
    @XmlEnumValue("Withdrawn")
    WITHDRAWN("Withdrawn"),
    @XmlEnumValue("Administratively Complete")
    ADMINISTRATIVELY_COMPLETE("Administratively Complete"),
    @XmlEnumValue("Completed")
    COMPLETED("Completed");
    private final String value;

    RecruitmentStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecruitmentStatus fromValue(String v) {
        for (RecruitmentStatus c: RecruitmentStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
