//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.nih.nci.po.webservices.types.CountryISO31661Alpha3Code;


/**
 * Trial Regulatory Information. Required only for trials
 * 				that require uploads into ClinicalTrials.gov.
 * 			
 * 
 * <p>Java class for RegulatoryInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulatoryInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{gov.nih.nci.po.webservices.types.trimmed}CountryISO-3166-1-alpha-3-Code"/>
 *         &lt;element name="authorityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fdaRegulated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="section801" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="delayedPosting" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dataMonitoringCommitteeAppointed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulatoryInformation", propOrder = {
    "country",
    "authorityName",
    "fdaRegulated",
    "section801",
    "delayedPosting",
    "dataMonitoringCommitteeAppointed"
})
public class RegulatoryInformation {

    @XmlElement(required = true)
    protected CountryISO31661Alpha3Code country;
    @XmlElement(required = true)
    protected String authorityName;
    protected boolean fdaRegulated;
    protected boolean section801;
    protected boolean delayedPosting;
    protected boolean dataMonitoringCommitteeAppointed;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryISO31661Alpha3Code }
     *     
     */
    public CountryISO31661Alpha3Code getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryISO31661Alpha3Code }
     *     
     */
    public void setCountry(CountryISO31661Alpha3Code value) {
        this.country = value;
    }

    /**
     * Gets the value of the authorityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * Sets the value of the authorityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorityName(String value) {
        this.authorityName = value;
    }

    /**
     * Gets the value of the fdaRegulated property.
     * 
     */
    public boolean isFdaRegulated() {
        return fdaRegulated;
    }

    /**
     * Sets the value of the fdaRegulated property.
     * 
     */
    public void setFdaRegulated(boolean value) {
        this.fdaRegulated = value;
    }

    /**
     * Gets the value of the section801 property.
     * 
     */
    public boolean isSection801() {
        return section801;
    }

    /**
     * Sets the value of the section801 property.
     * 
     */
    public void setSection801(boolean value) {
        this.section801 = value;
    }

    /**
     * Gets the value of the delayedPosting property.
     * 
     */
    public boolean isDelayedPosting() {
        return delayedPosting;
    }

    /**
     * Sets the value of the delayedPosting property.
     * 
     */
    public void setDelayedPosting(boolean value) {
        this.delayedPosting = value;
    }

    /**
     * Gets the value of the dataMonitoringCommitteeAppointed property.
     * 
     */
    public boolean isDataMonitoringCommitteeAppointed() {
        return dataMonitoringCommitteeAppointed;
    }

    /**
     * Sets the value of the dataMonitoringCommitteeAppointed property.
     * 
     */
    public void setDataMonitoringCommitteeAppointed(boolean value) {
        this.dataMonitoringCommitteeAppointed = value;
    }

}
