//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 12:41:09 PM EST 
//


package gov.nih.nci.pa.webservices.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrialCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrialCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="National"/>
 *     &lt;enumeration value="Externally Peer-Reviewed"/>
 *     &lt;enumeration value="Institutional"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrialCategory")
@XmlEnum
public enum TrialCategory {

    @XmlEnumValue("National")
    NATIONAL("National"),
    @XmlEnumValue("Externally Peer-Reviewed")
    EXTERNALLY_PEER_REVIEWED("Externally Peer-Reviewed"),
    @XmlEnumValue("Institutional")
    INSTITUTIONAL("Institutional");
    private final String value;

    TrialCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrialCategory fromValue(String v) {
        for (TrialCategory c: TrialCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
