DROP SEQUENCE IF EXISTS serial;
CREATE SEQUENCE serial START 901;
DELETE FROM country ;
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'RS', 'SRB', 'Serbia', '688' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IR', 'IRN', 'Iran (Islamic Republic Of)', '364' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IQ', 'IRQ', 'Iraq', '368' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IE', 'IRL', 'Ireland', '372' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IL', 'ISR', 'Israel', '376' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IT', 'ITA', 'Italy', '380' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'JM', 'JAM', 'Jamaica', '388' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'JP', 'JPN', 'Japan', '392' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KE', 'KEN', 'Kenya', '404' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KI', 'KIR', 'Kiribati', '296' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KP', 'PRK', 'Korea, Democratic Peoples Replublic of', '408' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KS', 'KOR', 'Korea, Republic of', '410' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KW', 'KWT', 'Kuwait', '414' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KG', 'KGZ', 'Kyrgyzstan', '417' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LA', 'LAO', 'Lao Peoples Democratic Republic', '418' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LV', 'LVA', 'Latvia', '428' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LB', 'LBN', 'Lebanon', '422' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LS', 'LSO', 'Lesotho', '426' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LR', 'LBR', 'Liberia', '430' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LY', 'LBY', 'Libyan Arab Jamahiriya', '434' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LI', 'LIE', 'Liechtenstein', '438' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LT', 'LTU', 'Lithuania', '440' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LU', 'LUX', 'Luxembourg', '442' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MO', 'MAC', 'Macau', '446' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MK', 'MKD', 'Macedonia', '807' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MG', 'MDG', 'Madagascar', '450' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MW', 'MWI', 'Malawi', '454' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MY', 'MYS', 'Malaysia', '458' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MV', 'MDV', 'Maldives', '462' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ML', 'MLI', 'Mali', '466' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MT', 'MLT', 'Malta', '470' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MH', 'MHL', 'Marshall Islands', '584' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MQ', 'MTQ', 'Martinique', '474' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MR', 'MRT', 'Mauritania', '478' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MU', 'MUS', 'Mauritius', '480' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'YT', 'MYT', 'Mayotte', '175' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MX', 'MEX', 'Mexico', '484' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FM', 'FSM', 'Micronesia, Federated States of', '583' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MD', 'MDA', 'Moldova, Republic of', '498' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MC', 'MCO', 'Monaco', '492' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MN', 'MNG', 'Mongolia', '496' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MS', 'MSR', 'Montserrat', '500' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MA', 'MAR', 'Morocco', '504' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MZ', 'MOZ', 'Mozambique', '508' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MM', 'MMR', 'Myanmar', '104' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NA', 'NAM', 'Namibia', '516' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NR', 'NRU', 'Nauru', '520' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NP', 'NPL', 'Nepal', '524' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NL', 'NLD', 'Netherlands', '528' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AN', 'ANT', 'Netherlands Antilles', '530' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NC', 'NCL', 'New Caledonia', '540' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NZ', 'NZL', 'New Zealand', '554' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NI', 'NIC', 'Nicaragua', '558' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NE', 'NER', 'Niger', '562' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NG', 'NGA', 'Nigeria', '566' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NU', 'NIU', 'Niue', '570' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NF', 'NFK', 'Norfolk Island', '574' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MP', 'MNP', 'Northern Mariana Islands', '580' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'NO', 'NOR', 'Norway', '578' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'OM', 'OMN', 'Oman', '512' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PK', 'PAK', 'Pakistan', '586' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PW', 'PLW', 'Palau', '585' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PS', 'PSE', 'Palestinian Territory', '275' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PA', 'PAN', 'Panama', '591' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PG', 'PNG', 'Papua New Guinea', '598' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PY', 'PRY', 'Paraguay', '600' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PE', 'PER', 'Peru', '604' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PH', 'PHL', 'Philippines', '608' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'JO', 'JOR', 'Jordan', '400' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KZ', 'KAZ', 'Kazakhstan', '398' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PN', 'PCN', 'Pitcairn', '612' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PL', 'POL', 'Poland', '616' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PT', 'PRT', 'Portugal', '620' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PR', 'PRI', 'Puerto Rico', '630' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'QA', 'QAT', 'Qatar', '634' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'RE', 'REU', 'Reunion', '638' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'RO', 'ROU', 'Romania', '642' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'RU', 'RUS', 'Russian Federation', '643' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'RW', 'RWA', 'Rwanda', '646' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KN', 'KNA', 'Saint Kitts And Nevis', '659' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LC', 'LCA', 'Saint Lucia', '662' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VC', 'VCT', 'Saint Vincent And The Grenadines', '670' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'WS', 'WSM', 'Samoa', '882' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SM', 'SMR', 'San Marino', '674' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ST', 'STP', 'Sao Tome And Principe', '678' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SA', 'SAU', 'Saudi Arabia', '682' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SN', 'SEN', 'Senegal', '686' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SC', 'SYC', 'Seychelles', '690' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SL', 'SLE', 'Sierra Leone', '694' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SG', 'SGP', 'Singapore', '702' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SK', 'SVK', 'Slovakia (Slovak Republic)', '703' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SI', 'SVN', 'Slovenia', '705' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SB', 'SLB', 'Solomon Islands', '090' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SO', 'SOM', 'Somalia', '706' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ZA', 'ZAF', 'South Africa', '710' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GS', 'SGS', 'South Georgia And The South Sandwich Islands', '239' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ES', 'ESP', 'Spain', '724' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'LK', 'LKA', 'Sri Lanka', '144' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SD', 'SDN', 'Sudan', '736' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SR', 'SUR', 'Suriname', '740' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SJ', 'SJM', 'Svalbard And Jan Mayen Islands', '744' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SZ', 'SWZ', 'Swaziland', '748' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SE', 'SWE', 'Sweden', '752' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CH', 'CHE', 'Switzerland', '756' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SY', 'SYR', 'Syrian Arab Republic', '760' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TW', 'TWN', 'Taiwan', '158' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TJ', 'TJK', 'Tajikistan', '762' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TZ', 'TZA', 'Tanzania', '834' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TH', 'THA', 'Thailand', '764' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TG', 'TGO', 'Togo', '768' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TK', 'TKL', 'Tokelau', '772' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TO', 'TON', 'Tonga', '776' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TT', 'TTO', 'Trinidad And Tobago', '780' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TN', 'TUN', 'Tunisia', '788' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TR', 'TUR', 'Turkey', '792' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TM', 'TKM', 'Turkmenistan', '795' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TC', 'TCA', 'Turks And Caicos Islands', '796' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TV', 'TUV', 'Tuvalu', '798' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'UG', 'UGA', 'Uganda', '800' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'UA', 'UKR', 'Ukraine', '804' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HU', 'HUN', 'Hungary', '348' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IS', 'ISL', 'Iceland', '352' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IN', 'IND', 'India', '356' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AE', 'ARE', 'United Arab Emirates', '784' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GB', 'GBR', 'United Kingdom', '826' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'US', 'USA', 'United States', '840' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'UM', 'UMI', 'United States Minor Outlying Islands', '581' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'UY', 'URY', 'Uruguay', '858' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'UZ', 'UZB', 'Uzbekistan', '860' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VU', 'VUT', 'Vanuatu', '548' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VE', 'VEN', 'Venezuela', '862' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VN', 'VNM', 'Viet Nam', '704' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VG', 'VGB', 'Virgin Islands (British)', '092' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VI', 'VIR', 'Virgin Islands (U.S.)', '850' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'WF', 'WLF', 'Wallis And Futuna Islands', '876' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'EH', 'ESH', 'Western Sahara', '732' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'YE', 'YEM', 'Yemen', '887' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ZM', 'ZMB', 'Zambia', '894' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ZW', 'ZWE', 'Zimbabwe', '716' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AF', 'AFG', 'Afghanistan', '004' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AL', 'ALB', 'Albania', '008' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DZ', 'DZA', 'Algeria', '012' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AS', 'ASM', 'American Samoa', '016' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AD', 'AND', 'Andorra', '020' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AO', 'AGO', 'Angola', '024' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AI', 'AIA', 'Anguilla', '660' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AQ', 'ATA', 'Antarctica', '010' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AG', 'ATG', 'Antigua And Barbuda', '028' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AR', 'ARG', 'Argentina', '032' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AM', 'ARM', 'Armenia', '051' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AW', 'ABW', 'Aruba', '533' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AU', 'AUS', 'Australia', '036' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AT', 'AUT', 'Austria', '040' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AZ', 'AZE', 'Azerbaijan', '031' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BS', 'BHS', 'Bahamas', '044' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BH', 'BHR', 'Bahrain', '048' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BD', 'BGD', 'Bangladesh', '050' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BB', 'BRB', 'Barbados', '052' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BY', 'BLR', 'Belarus', '112' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BE', 'BEL', 'Belgium', '056' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BZ', 'BLZ', 'Belize', '084' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BJ', 'BEN', 'Benin', '204' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BM', 'BMU', 'Bermuda', '060' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BT', 'BTN', 'Bhutan', '064' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BO', 'BOL', 'Bolivia', '068' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BA', 'BIH', 'Bosnia And Herzegowina', '070' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BW', 'BWA', 'Botswana', '072' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BV', 'BVT', 'Bouvet Island', '074' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BR', 'BRA', 'Brazil', '076' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IO', 'IOT', 'British Indian Ocean Territory', '086' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BN', 'BRN', 'Brunei Darussalam', '096' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BG', 'BGR', 'Bulgaria', '100' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BF', 'BFA', 'Burkina Faso', '854' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BI', 'BDI', 'Burundi', '108' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KH', 'KHM', 'Cambodia', '116' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CM', 'CMR', 'Cameroon', '120' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CA', 'CAN', 'Canada', '124' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CV', 'CPV', 'Cape Verde', '132' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KY', 'CYM', 'Cayman Islands', '136' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CF', 'CAF', 'Central African Republic', '140' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TD', 'TCD', 'Chad', '148' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CL', 'CHL', 'Chile', '152' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CN', 'CHN', 'China', '156' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CX', 'CXR', 'Christmas Island', '162' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CC', 'CCK', 'Cocos (Keeling) Islands', '166' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CO', 'COL', 'Colombia', '170' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'KM', 'COM', 'Comoros', '174' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CG', 'COG', 'Congo', '178' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CD', 'COD', 'Congo, Democratic Republic of th', '180' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CK', 'COK', 'Cook Islands', '184' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CR', 'CRI', 'Costa Rica', '188' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CI', 'CIV', 'Cote D Ivoire', '384' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HR', 'HRV', 'Croatia', '191' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CU', 'CUB', 'Cuba', '192' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CY', 'CYP', 'Cyprus', '196' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'CZ', 'CZE', 'Czech Republic', '203' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DK', 'DNK', 'Denmark', '208' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DJ', 'DJI', 'Djibouti', '262' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DM', 'DMA', 'Dominica', '212' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DO', 'DOM', 'Dominican Republic', '214' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'EC', 'ECU', 'Ecuador', '218' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'EG', 'EGY', 'Egypt', '818' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SV', 'SLV', 'El Salvador', '222' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GQ', 'GNQ', 'Equatorial Guinea', '226' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ER', 'ERI', 'Eritrea', '232' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'EE', 'EST', 'Estonia', '233' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ET', 'ETH', 'Ethiopia', '231' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FK', 'FLK', 'Falkland Islands (Malvinas)', '238' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FO', 'FRO', 'Faroe Islands', '234' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FJ', 'FJI', 'Fiji', '242' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FI', 'FIN', 'Finland', '246' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'FR', 'FRA', 'France', '250' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GF', 'GUF', 'French Guiana', '254' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PF', 'PYF', 'French Polynesia', '258' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TF', 'ATF', 'French Southern Territories', '260' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GA', 'GAB', 'Gabon', '266' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GM', 'GMB', 'Gambia', '270' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GE', 'GEO', 'Georgia', '268' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'DE', 'DEU', 'Germany', '276' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GH', 'GHA', 'Ghana', '288' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GI', 'GIB', 'Gibraltar', '292' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GR', 'GRC', 'Greece', '300' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GL', 'GRL', 'Greenland', '304' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GD', 'GRD', 'Grenada', '308' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GP', 'GLP', 'Guadeloupe', '312' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GU', 'GUM', 'Guam', '316' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GT', 'GTM', 'Guatemala', '320' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GN', 'GIN', 'Guinea', '324' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GW', 'GNB', 'Guinea-Bissau', '624' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GY', 'GUY', 'Guyana', '328' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HT', 'HTI', 'Haiti', '332' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HM', 'HMD', 'Heard And Mc Donald Islands', '334' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HN', 'HND', 'Honduras', '340' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'HK', 'HKG', 'Hong Kong', '344' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ID', 'IDN', 'Indonesia', '360' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'AX', 'ALA', 'Aland Islands', '248' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'GG', 'GGY', 'Guernsey', '831' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'VA', 'VAT', 'Holy See (Vatican City State)', '336' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'IM', 'IMN', 'Isle of Man', '833' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'JE', 'JEY', 'Jersey', '832' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'ME', 'MNE', 'Montenegro', '499' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'BL', 'BLM', 'Saint Barthelemy', '652' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'SH', 'SHN', 'Saint Helena', '654' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'MF', 'MAF', 'Saint Martin (French Part)', '663' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'PM', 'SPM', 'Saint Pierre and Miquelon', '666' );
INSERT INTO public.country (identifier, alpha2, alpha3, name, numeric) VALUES ( nextval('serial'), 'TL', 'TLS', 'Timor-Leste', '626' );
