--This will remove the client, Subscriber and Publisher groups from grid grouper syncing if they have been added.
DELETE FROM CSM_REMOTE_GROUP_SYNC_RECORD WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'Subscriber');
DELETE FROM CSM_REMOTE_GROUP_SYNC_RECORD WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'Publisher');
DELETE FROM CSM_REMOTE_GROUP_SYNC_RECORD WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'client');
DELETE FROM CSM_REMOTE_GROUP WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'Subscriber');
DELETE FROM CSM_REMOTE_GROUP WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'Publisher');
DELETE FROM CSM_REMOTE_GROUP WHERE GROUP_ID = (SELECT GROUP_ID FROM CSM_GROUP WHERE GROUP_NAME = 'client');