DROP TABLE IF EXISTS STG_DW_STUDY_PARTICIPATING_SITE_ACCRUAL_STATUS;
CREATE TABLE STG_DW_STUDY_PARTICIPATING_SITE_ACCRUAL_STATUS ( 
    STATUS character varying(50),
    STATUS_DATE timestamp,
    DATE_CREATED timestamp,
    DATE_LAST_UPDATED timestamp,
    COMMENTS character varying(2000),
    INTERNAL_SYSTEM_ID INTEGER,
    STUDY_SITE_ID INTEGER,
    USER_CREATED character varying(500),
    USER_LAST_UPDATED character varying(500),
    PRIMARY KEY (INTERNAL_SYSTEM_ID)
);
--Create history table
CREATE TABLE IF NOT EXISTS HIST_DW_STUDY_PARTICIPATING_SITE_ACCRUAL_STATUS ( 
 RUN_ID TIMESTAMP,
    STATUS character varying(50),
    STATUS_DATE timestamp,
    DATE_CREATED timestamp,
    DATE_LAST_UPDATED timestamp,
    COMMENTS character varying(2000),
    INTERNAL_SYSTEM_ID INTEGER,
    STUDY_SITE_ID INTEGER,
    USER_CREATED character varying(500),
    USER_LAST_UPDATED character varying(500)
);

