DROP TABLE IF EXISTS STG_DW_STUDY_SECONDARY_PURPOSE;
CREATE TABLE STG_DW_STUDY_SECONDARY_PURPOSE (
    SECONDARY_PURPOSE_NAME character varying(32),
    SECONDARY_PURPOSE_OTHER_TEXT character varying(1000),
    NCI_ID character varying(255)
);
--Create history table
CREATE TABLE IF NOT EXISTS HIST_DW_STUDY_SECONDARY_PURPOSE (
   RUN_ID TIMESTAMP,
    SECONDARY_PURPOSE_NAME character varying(32),
    SECONDARY_PURPOSE_OTHER_TEXT character varying(1000),
    NCI_ID character varying(255)
);