update anatomic_sites set code ='Anus', display_name='Anus' where code ='anus';
update anatomic_sites set code ='Bones and Joints', display_name='Bones and Joints' where code ='bones and joints';
update anatomic_sites set code ='Brain and Nervous System', display_name='Brain and Nervous System' where code ='brain and nervous system';
update anatomic_sites set code ='Breast - Female', display_name='Breast - Female' where code ='breast - female';
update anatomic_sites set code ='Breast - Male', display_name='Breast - Male' where code ='breast - male';
update anatomic_sites set code ='Cervix', display_name='Cervix' where code ='cervix';
update anatomic_sites set code ='Colon', display_name='Colon' where code ='colon';
update anatomic_sites set code ='Corpus Uteri', display_name='Corpus Uteri' where code ='corpus uteri';
update anatomic_sites set code ='Esophagus', display_name='Esophagus' where code ='esophagus';
update anatomic_sites set code ='Eye and Orbit', display_name='Eye and Orbit' where code ='eye and orbit';
update anatomic_sites set code ='Hodgkin''s Lymphoma', display_name='Hodgkin''s Lymphoma' where code ='hodgkin''s lymphoma';
update anatomic_sites set code ='Ill-Defined Sites', display_name='Ill-Defined Sites' where code ='Ill-Defined Sites';
update anatomic_sites set code ='Kaposi''s Sarcoma', display_name='Kaposi''s Sarcoma' where code ='kaposi''s sarcoma';
update anatomic_sites set code ='Kidney', display_name='Kidney' where code ='kidney';
update anatomic_sites set code ='Larynx', display_name='Larynx' where code ='larynx';
update anatomic_sites set code ='Leukemia, not otherwise specified', display_name='Leukemia, not otherwise specified' where code ='Leukemia, not otherwise specified';
update anatomic_sites set code ='Leukemia, other', display_name='Leukemia, other' where code ='Leukemia, other';
update anatomic_sites set code ='Lip, Oral Cavity and Pharynx', display_name='Lip, Oral Cavity and Pharynx' where code ='lip, oral cavity and pharynx';
update anatomic_sites set code ='Liver', display_name='Liver' where code ='liver';
update anatomic_sites set code ='Lung', display_name='Lung' where code ='lung';
update anatomic_sites set code ='Lymphoid Leukemia', display_name='Lymphoid Leukemia' where code ='lymphoid leukemia';
update anatomic_sites set code ='Melanoma, Skin', display_name='Melanoma, Skin' where code ='melanoma, skin';
update anatomic_sites set code ='Multiple', display_name='Multiple' where code ='multiple';
update anatomic_sites set code ='Multiple Myeloma', display_name='Multiple Myeloma' where code ='multiple myeloma';
update anatomic_sites set code ='Mycosis Fungoides', display_name='Mycosis Fungoides' where code ='mycosis fungoides';
update anatomic_sites set code ='Myeloid and Monocytic Leukemia', display_name='Myeloid and Monocytic Leukemia' where code ='myeloid and moncytic leukemia';
update anatomic_sites set code ='Non-Hodgkin''s Lymphoma', display_name='Non-Hodgkin''s Lymphoma' where code ='non-hodgkin''s lymphoma';
update anatomic_sites set code ='Other Digestive Organ', display_name='Other Digestive Organ' where code ='other digestive organs';
update anatomic_sites set code ='Other Endocrine System', display_name='Other Endocrine System' where code ='other endocrine system';
update anatomic_sites set code ='Other Female Genital', display_name='Other Female Genital' where code ='other female genital';
update anatomic_sites set code ='Other Hematopoietic', display_name='Other Hematopoietic' where code ='Other Hematopoietic';
update anatomic_sites set code ='Other Male Genital', display_name='Other Male Genital' where code ='other male genital';
update anatomic_sites set code ='Other Respiratory/Intrathoracic Organs', display_name='Other Respiratory/Intrathoracic Organs' where code ='other respiratory and intrathoracic organs';
update anatomic_sites set code ='Other Skin', display_name='Other Skin' where code ='other skin';
update anatomic_sites set code ='Other Urinary', display_name='Other Urinary' where code ='other urinary';
update anatomic_sites set code ='Ovary', display_name='Ovary' where code ='ovary';
update anatomic_sites set code ='Pancreas', display_name='Pancreas' where code ='pancreas';
update anatomic_sites set code ='Prostate', display_name='Prostate' where code ='prostate';
update anatomic_sites set code ='Rectum', display_name='Rectum' where code ='rectum';
update anatomic_sites set code ='Small Intestine', display_name='Small Intestine' where code ='small intestine';
update anatomic_sites set code ='Soft Tissue / Sarcoma', display_name='Soft Tissue / Sarcoma' where code ='soft tissue';
update anatomic_sites set code ='Stomach', display_name='Stomach' where code ='stomach';
update anatomic_sites set code ='Thyroid', display_name='Thyroid' where code ='thyroid';
update anatomic_sites set code ='Unknown Sites', display_name='Unknown Sites' where code ='Unknown Sites';
update anatomic_sites set code ='Urinary Bladder', display_name='Urinary Bladder' where code ='urinary bladder';
