UPDATE PERFORMED_OBSERVATION_RESULT SET RESULT_CODE='Other' WHERE TYPE_CODE = 'CAUSE_OF_DEATH_AS_DETERMINED_BY_AUTOPSY';
UPDATE PERFORMED_OBSERVATION_RESULT SET STAGE_CODING_SYSTEM='AJCC' WHERE STAGE_CODING_SYSTEM IN ('SEER');

UPDATE PERFORMED_ACTIVITY SET DOSE_MODIFICATION_TYPE='Not Applicable' WHERE DOSE_MODIFICATION_TYPE IN('Dose Delayed', 'Dose Dis-continued','Dose Missed','Dose Modified','Dose Restarted');
UPDATE PERFORMED_ACTIVITY SET REASON_CODE='OTHER' WHERE PERFORMED_ACTIVITY_TYPE='PerformedSubjectMilestone' AND NAME_CODE='OFF_TREATMENT';