--DROP TABLE TEMP_STUDY_FUNDING ;
CREATE TABLE TEMP_STUDY_FUNDING (
    IDENTIFIER SERIAL NOT NULL,
    FUNDING_MECHANISM_CODE CHARACTER VARYING(200),
    NIH_INSTITUTE_CODE CHARACTER VARYING(200),
    NCI_DIVISION_PROGRAM_CODE CHARACTER VARYING(200),
    SERIAL_NUMBER CHARACTER VARYING(6),
    DATE_LAST_CREATED TIMESTAMP WITHOUT TIME ZONE ,
    USER_LAST_CREATED CHARACTER VARYING(200) ,
    USER_LAST_UPDATED CHARACTER VARYING(200),
    DATE_LAST_UPDATED TIMESTAMP WITHOUT TIME ZONE, 
    TEMP_STUDY_PROTOCOL_IDENTIFIER BIGINT NOT NULL,
    CONSTRAINT TEMP_STUDY_FUNDING_PKEY PRIMARY KEY (IDENTIFIER),
    CONSTRAINT FK_TEMP_STUDY_FUNDING_TEMP_STUDY_PROTOCOL FOREIGN KEY (TEMP_STUDY_PROTOCOL_IDENTIFIER)
    REFERENCES TEMP_STUDY_PROTOCOL (IDENTIFIER) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE CASCADE);