ALTER TABLE PERFORMED_OBSERVATION_RESULT DROP COLUMN MEASURABLE_INDICATOR;
ALTER TABLE PERFORMED_OBSERVATION_RESULT ADD COLUMN MEASURABLE_INDICATOR VARCHAR(200);

ALTER TABLE ACTIVITY_RELATIONSHIP DROP COLUMN PLANNED_ACTIVITY_IDENTIFIER;
ALTER TABLE ACTIVITY_RELATIONSHIP DROP COLUMN PERFORMED_ACTIVITY_IDENTIFIER;
ALTER TABLE ACTIVITY_RELATIONSHIP  ADD COLUMN SOURCE_PERFORMED_ACTIVITY_IDENTIFIER BIGINT;
ALTER TABLE ACTIVITY_RELATIONSHIP  ADD COLUMN TARGET_PERFORMED_ACTIVITY_IDENTIFIER BIGINT;
 
ALTER TABLE ACTIVITY_RELATIONSHIP ADD CONSTRAINT FK_ACTIVITY_RELATIONSHIP_SOURCE_PLANNED_ACTIVITY
FOREIGN KEY (SOURCE_PERFORMED_ACTIVITY_IDENTIFIER) REFERENCES PERFORMED_ACTIVITY (IDENTIFIER)
ON DELETE CASCADE; 

ALTER TABLE ACTIVITY_RELATIONSHIP ADD CONSTRAINT FK_ACTIVITY_RELATIONSHIP_TARGET_PERFORMED_ACTIVITY
FOREIGN KEY (TARGET_PERFORMED_ACTIVITY_IDENTIFIER) REFERENCES PERFORMED_ACTIVITY (IDENTIFIER)
ON DELETE CASCADE; 

ALTER TABLE PERFORMED_OBSERVATION_RESULT ADD CONSTRAINT FK_PERFORMED_OBSERVATION_RESULT_PERFORMED_ACTIVITY_IDENTIFIER
FOREIGN KEY (PERFORMED_ACTIVITY_IDENTIFIER) REFERENCES PERFORMED_ACTIVITY (IDENTIFIER)
ON DELETE CASCADE; 