DROP TABLE IF EXISTS ASSESSMENT_TYPE ;

CREATE TABLE ASSESSMENT_TYPE  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE ASSESSMENT_TYPE ADD CONSTRAINT UK_ASSESSMENT_TYPE_CODE  UNIQUE (CODE); 

DROP TABLE IF EXISTS TUMOR_MARKER ;

CREATE TABLE TUMOR_MARKER  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE TUMOR_MARKER ADD CONSTRAINT UK_TUMOR_MARKER_CODE  UNIQUE (CODE); 

DROP TABLE IF EXISTS ANATOMIC_SITES ;

CREATE TABLE ANATOMIC_SITES  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE ANATOMIC_SITES ADD CONSTRAINT UK_ANATOMIC_SITES_CODE  UNIQUE (CODE); 

DROP TABLE IF EXISTS LESION_LOCATION_ANATOMIC_SITE ;

CREATE TABLE LESION_LOCATION_ANATOMIC_SITE  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE LESION_LOCATION_ANATOMIC_SITE ADD CONSTRAINT UK_LESION_LOCATION_ANATOMIC_SITE_CODE  UNIQUE (CODE); 

DROP TABLE IF EXISTS PROCEDURE_NAME ;

CREATE TABLE PROCEDURE_NAME  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE PROCEDURE_NAME ADD CONSTRAINT UK_PROCEDURE_NAME_CODE  UNIQUE (CODE); 