DROP TABLE IF EXISTS TARGET_SITE ;

CREATE TABLE TARGET_SITE  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE TARGET_SITE ADD CONSTRAINT UK_TARGET_SITE_CODE  UNIQUE (CODE); 

DROP TABLE IF EXISTS METHOD_CODE ;

CREATE TABLE METHOD_CODE  (
    IDENTIFIER SERIAL NOT NULL,
    CODE  VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(1000) NOT NULL,    
    DESCRIPTION VARCHAR(2000),
    CONCEPT_ID VARCHAR(200),
    PUBLIC_ID  VARCHAR(200),
    CODING_SYSTEM  VARCHAR(200),
    CODING_SYSTEM_NAME  VARCHAR(200),
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER)
);

ALTER TABLE METHOD_CODE ADD CONSTRAINT UK_METHOD_CODE_CODE  UNIQUE (CODE); 