ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN STRUCTURED_INDICATOR BOOLEAN;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN TEXT_VALUE  VARCHAR(200);



ALTER TABLE PLANNED_ACTIVITY  RENAME COLUMN VALUE TO MIN_VALUE;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN MIN_UNIT  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN MAX_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN MAX_UNIT  VARCHAR(200);


UPDATE PLANNED_ACTIVITY SET MIN_UNIT = unit;

UPDATE PLANNED_ACTIVITY SET MAX_UNIT = unit;