ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MIN_UNIT;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MIN_UNIT
FOREIGN KEY (DOSE_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MAX_UNIT; 

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MAX_UNIT
FOREIGN KEY (DOSE_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MIN_UNIT;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MIN_UNIT
FOREIGN KEY (DOSE_TOTAL_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT(CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MAX_UNIT;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MAX_UNIT
FOREIGN KEY (DOSE_TOTAL_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FORM_CODE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FORM_CODE
FOREIGN KEY (DOSE_FORM_CODE) REFERENCES DOSE_FORM (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FREQUENCY_CODE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FREQUENCY_CODE
FOREIGN KEY (DOSE_FREQUENCY_CODE) REFERENCES DOSE_FREQUENCY (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY DROP CONSTRAINT FK_PLANNED_ACTIVITY_ROUTE_OF_ADMINISTRATION_CODE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_ROUTE_OF_ADMINISTRATION_CODE
FOREIGN KEY (ROUTE_OF_ADMINISTRATION_CODE) REFERENCES ROUTE_OF_ADMINISTRATION (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN APPROACH_SITE_CODE  VARCHAR(200);

ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN TARGET_SITE_CODE  VARCHAR(200);

ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN METHOD_CODE  VARCHAR(200);

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_TARGET_SITE_CODE
FOREIGN KEY (TARGET_SITE_CODE) REFERENCES TARGET_SITE (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_APPROACH_SITE_CODE
FOREIGN KEY (APPROACH_SITE_CODE) REFERENCES TARGET_SITE (CODE) ON DELETE RESTRICT;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_METHOD_CODE
FOREIGN KEY (METHOD_CODE) REFERENCES METHOD_CODE (CODE) ON DELETE RESTRICT;


UPDATE PLANNED_ACTIVITY SET CATEGORY_CODE='SUBSTANCE_ADMINISTRATION' where SUBCATEGORY_CODE = 'DRUG' OR SUBCATEGORY_CODE = 'RADIATION';
UPDATE PLANNED_ACTIVITY SET CATEGORY_CODE='PLANNED_PROCEDURE' where SUBCATEGORY_CODE = 'PROCEDURE_SURGERY';
UPDATE PLANNED_ACTIVITY SET PLANNED_ACTIVITY_TYPE = 'PlannedSubstanceAdministration' where CATEGORY_CODE='SUBSTANCE_ADMINISTRATION';
UPDATE PLANNED_ACTIVITY SET PLANNED_ACTIVITY_TYPE = 'PlannedProcedure' where CATEGORY_CODE='PLANNED_PROCEDURE';