
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_MIN_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_MIN_UNIT  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_MAX_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_MAX_UNIT  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_DESCRIPTION  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_FORM_CODE  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_FREQUENCY_CODE  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_REGIMEN  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_TOTAL_MIN_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_TOTAL_MIN_UNIT  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_TOTAL_MAX_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_TOTAL_MAX_UNIT  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN ROUTE_OF_ADMINISTRATION_CODE  VARCHAR(200);
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_DURATION_VALUE  NUMERIC;
ALTER TABLE PLANNED_ACTIVITY  ADD COLUMN DOSE_DURATION_UNIT  VARCHAR(200);

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MIN_UNIT
FOREIGN KEY (DOSE_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_MAX_UNIT
FOREIGN KEY (DOSE_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MIN_UNIT
FOREIGN KEY (DOSE_TOTAL_MIN_UNIT) REFERENCES UNIT_OF_MEASUREMENT(CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_TOTAL_MAX_UNIT
FOREIGN KEY (DOSE_TOTAL_MAX_UNIT) REFERENCES UNIT_OF_MEASUREMENT (CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FORM_CODE
FOREIGN KEY (DOSE_FORM_CODE) REFERENCES DOSE_FORM (CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_DOSE_FREQUENCY_CODE
FOREIGN KEY (DOSE_FREQUENCY_CODE) REFERENCES DOSE_FREQUENCY (CODE) ON DELETE CASCADE;

ALTER TABLE PLANNED_ACTIVITY ADD CONSTRAINT FK_PLANNED_ACTIVITY_ROUTE_OF_ADMINISTRATION_CODE
FOREIGN KEY (ROUTE_OF_ADMINISTRATION_CODE) REFERENCES ROUTE_OF_ADMINISTRATION (CODE) ON DELETE CASCADE;
