DROP TABLE IF EXISTS MAPPING_IDENTIFIER;

CREATE TABLE MAPPING_IDENTIFIER (
    IDENTIFIER SERIAL NOT NULL,
    IDENTIFIER_NAME VARCHAR(200),
    FROM_IDENTIFIER BIGINT NOT NULL,
    TO_IDENTIFIER BIGINT NOT NULL,
    STUDY_PROTOCOL_IDENTIFIER BIGINT NOT NULL,
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200),
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200),
    PRIMARY KEY (IDENTIFIER) 
);