DROP TABLE IF EXISTS STUDY_SITE_OVERALL_STATUS;

CREATE TABLE STUDY_SITE_OVERALL_STATUS
(
  IDENTIFIER SERIAL NOT NULL,
  STATUS_CODE CHARACTER VARYING(200) NOT NULL,
  STATUS_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  STUDY_SITE_IDENTIFIER BIGINT NOT NULL,
  DATE_LAST_CREATED TIMESTAMP WITHOUT TIME ZONE,
  USER_LAST_CREATED CHARACTER VARYING(200),
  DATE_LAST_UPDATED TIMESTAMP WITHOUT TIME ZONE,
  USER_LAST_UPDATED CHARACTER VARYING(200),
  PRIMARY KEY (IDENTIFIER)
);
ALTER TABLE STUDY_SITE_OVERALL_STATUS ADD CONSTRAINT FK_STUDY_SITE_STUDY_SITE_OVERALL_STATUS
FOREIGN KEY (STUDY_SITE_IDENTIFIER) REFERENCES STUDY_SITE (IDENTIFIER) ON DELETE CASCADE;
